Public Class EmployeesAll
    Sub New()


        InitializeComponent()

        ' This line of code is generated by Data Source Configuration Wizard
        '   EmployeesDataTableAdapter1.Fill(TrueTimeDataSet1.EmployeesData)
        ' This line of code is generated by Data Source Configuration Wizard
        '   EmployeesData1TableAdapter1.Fill(TrueTimeDataSet2.EmployeesData1)
        ' This line of code is generated by Data Source Configuration Wizard
        EmployeesDataTableAdapter2.Fill(TrueTimeDataSet2.EmployeesData)
        colActive.FilterInfo = New DevExpress.XtraGrid.Columns.ColumnFilterInfo("[Active] =True")

    End Sub

    Private Sub EmployeesAll_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'TrueTimeDataSet2.Locations' table. You can move, or remove it, as needed.
        Me.LocationsTableAdapter.Fill(Me.TrueTimeDataSet2.Locations)

        Me.KeyPreview = True
    End Sub

    Private Sub AddVocation_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F5 Then
            RefreshData()
        ElseIf e.KeyCode = Keys.F6 Then
            AddNewEmployee()
        End If
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs)

        My.Forms.EmployeesEdit.Show()

    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs)
        My.Forms.EmployeesEdit.EmployeeIDTextEdit.Text = TextEmpID.Text
        EmployeesEdit.Show()

        My.Forms.EmployeesEdit.EmployeeNameTextEdit.Select()
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        My.Forms.EmployeesEdit.EmployeeIDTextEdit.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "EmployeeID"))
        EmployeesEdit.Show()
        My.Forms.EmployeesEdit.EmployeeNameTextEdit.Select()
    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs)
        EmployeesDataTableAdapter2.Fill(TrueTimeDataSet2.EmployeesData)
    End Sub

    Private Sub Label1_Click(sender As Object, e As EventArgs) Handles Label1.Click

    End Sub


    Private Sub AddNewEmployee()
        My.Forms.EmployeesEdit.Show()
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        '    My.Forms.EmployeesEdit.EmployeeIDTextEdit.Text = TextEmpID.Text


        '    If EmployeesEdit.ShowDialog() = DialogResult.OK Then
        '        MsgBox("ok")
        '    Else
        '        RefreshData()
        '    End If

        '    My.Forms.EmployeesEdit.EmployeeNameTextEdit.Select()
    End Sub

    Private Sub SimpleButton2_Click_1(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        RefreshData()
    End Sub
    Private Sub RefreshData()
        EmployeesDataTableAdapter2.Fill(TrueTimeDataSet2.EmployeesData)
        GridView1.BestFitColumns()
    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        ' My.Forms.EmployeesEdit.TextClean.Text = "-1"


        'If EmployeesEdit.ShowDialog() = DialogResult.OK Then
        '    MsgBox("ok")
        'Else
        '    RefreshData()
        'End If
        EmployeesEdit.Show()
        My.Forms.EmployeesEdit.ClearingEditEmployeeForm()
    End Sub

    Private Sub GetAccess_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        If CheckIfFormExist(Me.Name) = False Or HasAccessOnForm(Me.Name, "QueryAccess") = False Then
            Me.Close()
            MsgBox("لا يوجد صلاحية")
        End If
    End Sub

    Private Sub GridControl1_Click_1(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub RepositoryOpen_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryOpen.ButtonClick
        My.Forms.EmployeesEdit.EmployeeIDTextEdit.Text = CStr(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "EmployeeID"))
        EmployeesEdit.Show()
        My.Forms.EmployeesEdit.EmployeeNameTextEdit.Select()
    End Sub

    Private Sub DockPanel1_Click(sender As Object, e As EventArgs) Handles DockPanel1.Click

    End Sub
End Class