Imports DevExpress.XtraEditors
Imports DevExpress.XtraEditors.Controls
Imports DevExpress.XtraGrid
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraPrinting
Imports System.ComponentModel
Imports System.Data.SqlClient
Imports System.Data.SqlTypes
Imports System.IO

Public Class EmployeesEdit
    Public _New As Boolean


    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        '   EmployeesDataTableAdapter1.Fill(TrueTimeDataSet1.EmployeesData)
    End Sub

    Protected Overrides Sub OnLookAndFeelChangedCore()
        MyBase.OnLookAndFeelChangedCore()
        'ClientSize = dataLayoutControl1.Root.MinSize
    End Sub

    Private Sub EmployeesEdit_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'TrueTimeDataSet.EmployeesData1' table. You can move, or remove it, as needed.
        'Me.EmployeesData1TableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData1)
        'TODO: This line of code loads data into the 'TrueTimeDataSet.EmployeesTypes' table. You can move, or remove it, as needed.
        Me.EmployeesTypesTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesTypes)
        ProcessTypeSearch.Properties.DataSource = CreatPreccessTypeTable()
        AttFromMobileProcessTextEdit.Properties.DataSource = CreatAttPreccessFromMobileTable()
        If GlobalVariables._SystemLanguage = "Arabic" Then
            ProcessTypeSearch.Properties.DisplayMember = "ProccessType"
            ProcessTypeSearch.Properties.ValueMember = "TypeID"
        Else
            ProcessTypeSearch.Properties.DisplayMember = "ProccessTypeE"
            ProcessTypeSearch.Properties.ValueMember = "TypeID"
            ColProccessTypeE.Visible = True
            ColProccessType.Visible = False
        End If
        If GlobalVariables._UserAccessType = 2 Or GlobalVariables._UserAccessType = 96 Then
            TabNavigationPage6.PageVisible = False
        Else
            TabNavigationPage6.PageVisible = True
        End If
        Me.KeyPreview = True
        FillWeekDays()

        SalaryCurrencyLookUpEdit.Properties.DataSource = GetCurrency()

        Me.LocationsTableAdapter.Fill(Me.TrueTimeDataSet.Locations)
        Me.EmployeesItemsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesItems)
        Me.EmployeesDepartmentsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesDepartments)
        Me.EmployeesPositionsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesPositions)
        Me.EmployeesBranchesTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesBranches)
        SearchSections.Properties.DataSource = GetEmployeesSections()
        Dim _EmployeesTable As New DataTable
        _EmployeesTable = GetEmployeesList()
        Me.SearchManagerID.Properties.DataSource = _EmployeesTable
        Me.SearchManagerIDForweb.Properties.DataSource = _EmployeesTable
        RepositoryUserAccessType.Properties.DataSource = CreateUserAccessTypeTable()
        If GlobalVariables._SystemLanguage = "Arabic" Then
            RepositoryUserAccessType.Properties.DisplayMember = "UserType"
            RepositoryUserAccessType.Properties.ValueMember = "TypeID"
            ' ColProccessTypeE.Visible = False
        Else
            RepositoryUserAccessType.Properties.DisplayMember = "UserTypeE"
            RepositoryUserAccessType.Properties.ValueMember = "TypeID"
            ColUserTypeE.Visible = True
            ColUserType.Visible = False
        End If




        EmployeeIDTextEdit.Select()
        EmployeeNameTextEdit.Select()
        If _New = True Then
            ClearingEditEmployeeForm()
        End If

        If _New = True Then
            BarDefaultAccounts.Visibility = DevExpress.XtraBars.BarItemVisibility.Never
        End If
        GetRequiredDailyHouresPlans()
    End Sub
    Private Sub GetRequiredDailyHouresPlans()
        Dim sql As New SQLControl
        Dim sqlstring As String
        sqlstring = " SELECT id,PlaneCode,PlaneName from AttRequiredHoursPlanesNames order by ID "
        sql.SqlTrueTimeRunQuery(sqlstring)
        SearchRequiredPlans.Properties.DataSource = sql.SQLDS.Tables(0)
    End Sub

    Private Sub AddVocation_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F3 Then
            Saving()
        ElseIf e.KeyCode = Keys.F6 Then
            ClearingEditEmployeeForm()
        End If
    End Sub


    Private Sub SimpleButton1_Click_1(sender As Object, e As EventArgs)
        Saving()
        ClearingEditEmployeeForm()
    End Sub

    Private Sub Saving()
        If EmployeeIDTextEdit.Text = String.Empty Then XtraMessageBox.Show("الرقم الوظيفي فارغ") : Exit Sub
        If EmployeeNameTextEdit.Text = String.Empty Then XtraMessageBox.Show("اسم الموظف فارغ") : Exit Sub

        If DateOfEndDateEdit.EditValue IsNot Nothing Then
            If DateOfEndDateEdit.Text <> "01/01/2100" AndAlso DateOfEndDateEdit.EditValue IsNot Nothing Then
                If DateOfStartDateEdit.DateOnly > DateOfEndDateEdit.DateOnly Then
                    XtraMessageBox.Show(" تاريخ انتهاء العمل اقل من تاريخ بدء العمل  ")
                    Exit Sub
                End If
            End If
        End If

        'If DateOfStartDateEdit.EditValue IsNot Nothing AndAlso DateOfEndDateEdit.EditValue IsNot Nothing Then
        '    If DateOfEndDateEdit.Text <> "01/01/2100" Then
        '        If DateOfStartDateEdit.DateOnly > DateOfEndDateEdit.DateOnly Then
        '            XtraMessageBox.Show("Start date must be less than end date")
        '            Exit Sub
        '        End If
        '    End If

        'End If
        'If Not String.IsNullOrEmpty(Me.SalaryAccountNo.Text) Then
        '    '  If GlobalVariables.ConnectedWithTrueAccounting = True Then
        '    If CheckIfFoundInTrueAccounting(Me.SalaryAccountNo.EditValue) = True Then
        '        XtraMessageBox.Show("الحساب معرف بقائمة الذمم")
        '        Exit Sub
        '    End If
        '    ' End If
        '    'Else
        '    '    Try
        '    '        Dim sql As New SQLControl
        '    '        sql.SqlTrueAccountingRunQuery(" Select max(RefNo) as No from [dbo].[Referencess] ")
        '    '        Me.SalaryAccountNo.EditValue = CInt(sql.SQLDS.Tables(0).Rows(0).Item("No")) + 1
        '    '    Catch ex As Exception

        '    '    End Try

        'End If



        'If String.IsNullOrEmpty(DateOfStartDateEdit.Text) Then
        '    DateOfStartDateEdit.DateTime = CDate("1900-01-01")
        'End If
        'If String.IsNullOrEmpty(DateOfEndDateEdit.Text) Then
        '    DateOfEndDateEdit.DateTime = CDate("2100-01-01")
        'End If

        Try



            Me.Validate()
            Me.EmployeesDataBindingSource.EndEdit()
            Me.EmployeesDataBindingSource.CancelEdit()
            Me.TableAdapterManager.UpdateAll(Me.TrueTimeDataSet)

            UpdateOtherdata()

            If UserIDInAttFileTextEdit.Text = String.Empty Then
                Dim SQLString1 As String = " UPDATE EmployeesData set UserIDInAttFile= '" & EmployeeIDTextEdit.Text & "' where EmployeeID='" & EmployeeIDTextEdit.Text & "'"
                Dim sql As New SQLControl
                sql.SqlTrueTimeRunQuery(SQLString1)
            End If

            If Not String.IsNullOrEmpty(ProcessTypeSearch.Text) Then
                If ProcessTypeSearch.EditValue = "4" Then
                    Dim SQLString2 As String = " UPDATE EmployeesData set SubtractionLeavesAndLates= 0,AddBonusToSalary=0 where EmployeeID='" & EmployeeIDTextEdit.Text & "'"
                    Dim sql2 As New SQLControl
                    sql2.SqlTrueTimeRunQuery(SQLString2)
                End If
            End If

            SaveVocationsLimit()

            If Not PictureEmpPictureEdit.Image Is Nothing Then
                Dim m As New IO.MemoryStream
                PictureEmpPictureEdit.Image.Save(m, System.Drawing.Imaging.ImageFormat.Jpeg)
                Dim b() As Byte = m.ToArray()
                SavePhoto(b)
                '   Me.EmployeesDataTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData)
            End If

            'Me.EmployeesDataTableAdapter.FillByEmpID(Me.TrueTimeDataSet.EmployeesData, EmployeeIDTextEdit.Text)

            If GlobalVariables._SystemLanguage = "Arabic" Then
                MsgBoxShowSuccess(" لقد تم حفظ البيانات بنجاح ")
            Else
                XtraMessageBox.Show("Data Saved Succesfully")
            End If

            Me.Dispose()

        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub
    Private Sub UpdateOtherdata()
        Dim _BonusPerHourAmountOption As Integer
        If BonusPerHourAmountOption.EditValue = True Then
            _BonusPerHourAmountOption = 1
        Else
            _BonusPerHourAmountOption = 0
        End If
        If BonusPerHourAmountTextEdit.Text = "" Then
            BonusPerHourAmountTextEdit.EditValue = 0
        End If

        Dim _ManagerIDForWeb As Integer
        If SearchManagerIDForweb.Text <> "" Then
            _ManagerIDForWeb = SearchManagerIDForweb.EditValue
        Else
            If Me.SearchManagerID.Text <> "" Then
                _ManagerIDForWeb = Me.SearchManagerID.EditValue
            Else
                _ManagerIDForWeb = 0
            End If

        End If
        If SearchRequiredPlans.Text = "" Then SearchRequiredPlans.EditValue = 0
        Try
            Dim Sql As New SQLControl
            Dim SQLString As String = " UPDATE EmployeesData set  BonusPerHourAmount=" & BonusPerHourAmountTextEdit.EditValue & ",
                                               BonusPerHourAmountOption=" & _BonusPerHourAmountOption & ", 
                                               CalcBonusAfterMinutesInReqHoures=" & txtInReqHouresCalcBonusAfter.EditValue & " ,
                                               ManagerIDForWeb=" & _ManagerIDForWeb & ",
                                               SalaryPerDay=" & txtSalaryPerDay.EditValue & ",
                                               ActiveSavingFund=" & ActiveSavingFundCheckEdit.EditValue & ",
                                               RequiredHoursPlane=" & SearchRequiredPlans.EditValue & ",
                                               SectionsID=" & SearchSections.EditValue & ",
                                               AllowAddCustomerFromApp='" & AllowAddCustomerFromApp.EditValue & "',
                                               UniversitySonNo='" & TextExemptionsStudents.EditValue & "',
                                               AllowAddAttTrans='" & CheckAllowAddAttTrans.EditValue & "',
                                               CanEditPrice='" & AllowEditPrice.EditValue & "',
                                               ShowSalesinvoice = '" & AllowShowSalesinvoice.EditValue & "',
                                               ReceiptVoucher='" & AllowCreateReceiptVoucher.EditValue & "',
            CalAbsentInSalary ='" & CheckCalAbsentInSalary.EditValue & "'
                                        Where EmployeeID='" & EmployeeIDTextEdit.Text & "'"
            Sql.SqlTrueTimeRunQuery(SQLString)
        Catch ex As Exception
            MsgBoxShowError(" لم يتم تعديل البيانات  ")
        End Try
        changepassword()
    End Sub
    Private Sub SaveVocationsLimit()
        Dim IDD As Integer
        Dim DefaultBalanceForEmployee As Integer
        Dim EmpID As String = Me.EmployeeIDTextEdit.Text
        Dim Sql As New SQLControl
        If Not String.IsNullOrEmpty(EmpID) Then
            For i = 0 To BandedGridView1.RowCount - 1
                IDD = CInt(Me.BandedGridView1.GetRowCellValue(i, "IDD"))
                DefaultBalanceForEmployee = CInt(Me.BandedGridView1.GetRowCellValue(i, "DefaultBalanceForEmployee"))
                If DefaultBalanceForEmployee > 0 Then
                    If IDD <> 0 Then
                        Dim SQLUpdateString As String = "  update VocationsDefaultBalances set DefaultBalanceForEmployee =" & DefaultBalanceForEmployee & " where ID = " & IDD
                        Sql.SqlTrueTimeRunQuery(SQLUpdateString)
                    ElseIf IDD = 0 Then
                        Dim VocID As Integer = CInt(Me.BandedGridView1.GetRowCellValue(i, "VocID"))
                        Dim SqlInserString As String = "  insert into  VocationsDefaultBalances (VocID,EmployeeID,DefaultBalanceForEmployee) Values (" & VocID & ",'" & EmpID & "'," & DefaultBalanceForEmployee & " ) "
                        Sql.SqlTrueTimeRunQuery(SqlInserString)
                    End If
                End If
            Next
        End If
    End Sub
    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs)
        Try
            If Not Me.Validate() Then Exit Sub
            Me.EmployeesDataBindingSource.CancelEdit()
            Me.EmployeesDataBindingSource.MoveFirst()
        Catch ex As Exception

        End Try




    End Sub

    Private Sub SimpleButton7_Click(sender As Object, e As EventArgs)
        ClearingEditEmployeeForm()
    End Sub

    Public Sub ClearingEditEmployeeForm()

        Try
            If Not Me.Validate() Then Exit Sub
            Me.EmployeesDataBindingSource.CancelEdit()
            Me.EmployeesDataBindingSource.AddNew()
            Dim EmpID As Integer
            Dim SQLString As String = "Select max(EmployeeID) as EmpID from EmployeesData where EmployeeID <> 9999 and EmployeeID<>8888"
            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(SQLString)
            If sql.SQLDS.Tables(0).Rows.GetHashCode <> 0 Then EmpID = CInt(sql.SQLDS.Tables(0).Rows(0).Item("EmpID")) + 1
            EmployeeIDTextEdit.Text = EmpID
            ActiveCheckEdit.Checked = True
            Me.SubtractionLeavesAndLatesCheckEdit.Checked = True

            'DateOfStartDateEdit.DateTime = CDate("1900-01-01")
            'DateOfEndDateEdit.DateTime = CDate("2100-01-01")
            EmployeeNameTextEdit.Select()
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub SimpleButton8_Click(sender As Object, e As EventArgs)


        Try

            Dim a As New OpenFileDialog With {
                .Title = "Select your Image.",
                .InitialDirectory = "C:\",
                .Filter = "Image Files|*.gif;*.jpg;*.png;*.bmp;",
                .RestoreDirectory = False
            }

            If a.ShowDialog() = DialogResult.OK Then
                PictureEmpPictureEdit.Image = Image.FromFile(a.FileName)
            End If

            If Not PictureEmpPictureEdit.Image Is Nothing Then
                Dim m As New IO.MemoryStream
                PictureEmpPictureEdit.Image.Save(m, System.Drawing.Imaging.ImageFormat.Jpeg)
                Dim b() As Byte = m.ToArray()
                SavePhoto(b)
                '   Me.EmployeesDataTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData)
            End If
        Catch ex As Exception
            Exit Sub
        End Try



    End Sub



    Private Sub SavePhoto(ByVal bytPhoto As Byte())
        Try
            Dim SQLString As String = " UPDATE EmployeesData "
            SQLString = SQLString + " SET PictureEmp = @photo "
            If UserIDInAttFileTextEdit.Text = String.Empty Then SQLString = SQLString + "  , UserIDInAttFile= '" & EmployeeIDTextEdit.Text & "'"
            SQLString = SQLString + " WHERE EmployeeID = " & EmployeeIDTextEdit.Text
            Dim cn As New SqlConnection(My.Settings.TrueTimeConnectionString)
            cn.Open()
            Using cmd As New SqlClient.SqlCommand(SQLString, cn)
                cmd.Parameters.Add("@photo", SqlDbType.Image, bytPhoto.Length).Value = bytPhoto
                Try
                    cmd.ExecuteNonQuery()
                Catch SqlExceptionErr As SqlClient.SqlException
                    MessageBox.Show(SqlExceptionErr.Message)
                End Try
            End Using
            cn.Close()
        Catch ex As Exception
            ' XtraMessageBox.Show("خطا: لم يتم حفظ الصورة")
            MsgBox(ex.ToString)
        End Try
    End Sub



    Private Sub EmployeeIDTextEdit_Leave(sender As Object, e As EventArgs) Handles EmployeeIDTextEdit.Leave
        If String.IsNullOrEmpty(EmployeeIDTextEdit.Text) Then
            EmployeeIDTextEdit.Select()
        Else
            Try
                Dim oldvalue As String = EmployeeIDTextEdit.Text
                Me.EmployeesDataTableAdapter.FillByEmpID(Me.TrueTimeDataSet.EmployeesData, EmployeeIDTextEdit.Text)

                If EmployeesDataBindingSource.Count.ToString() > 0 Then
                Else
                    If Not Me.Validate() Then Exit Sub
                    Me.EmployeesDataBindingSource.CancelEdit()
                    Me.EmployeesDataBindingSource.AddNew()
                    EmployeeIDTextEdit.Text = oldvalue
                    ActiveCheckEdit.Checked = True
                    '   PictureEmpPictureEdit.Image = My.Resources.UserN




                End If
            Catch ex As Exception
                MsgBox(ex.ToString)
            End Try
        End If




    End Sub



    Private Sub DeleteData()
        Try
            Dim Msg As DialogResult = XtraMessageBox.Show("هل تريد حذف الموظف : " & EmployeeNameTextEdit.Text, "تأكيد", MessageBoxButtons.YesNo, MessageBoxIcon.Warning)
            If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub

            If IDTextEdit.EditValue <= 0 Then MsgBox("لا يوجد شيء لحذفه") : Exit Sub
            Dim i As Integer = 0
            Dim sql As New SQLControl
            Dim SQLString As String
            SQLString = "Select top(1) [USERID] from AttCHECKINOUT where [USERID] = '" & Me.UserIDInAttFileTextEdit.Text & "'"
            sql.SqlTrueTimeRunQuery(SQLString)
            If sql.SQLDS.Tables(0).Rows.Count > 0 Then MsgBox("الموظف له حركات دوام لا يمكن حذفه") : Exit Sub

            Dim sql2 As New SQLControl
            Dim SQLString2 As String
            SQLString2 = "Select top(1) EmployeeID from Vocations where [EmployeeID] = '" & Me.EmployeeIDTextEdit.Text & "'"
            sql2.SqlTrueTimeRunQuery(SQLString2)
            If sql2.SQLDS.Tables(0).Rows.Count > 0 Then MsgBox("الموظف له حركات اجازات لا يمكن حذفه") : Exit Sub


            Me.EmployeesDataBindingSource.RemoveCurrent()
            Me.EmployeesDataBindingSource.EndEdit()
            EmployeesDataTableAdapter.Update(TrueTimeDataSet.EmployeesData)
            TrueTimeDataSet.EmployeesData.AcceptChanges()

        Catch ex As Exception

        End Try
    End Sub

    Private Sub SearchLookUpEdit1_BeforePopup(sender As Object, e As EventArgs) Handles SearchLookUpEdit1.BeforePopup
        Me.EmployeesDataTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData)
    End Sub

    Private Sub SearchLookUpEdit1_Closed(sender As Object, e As ClosedEventArgs) Handles SearchLookUpEdit1.Closed

        Try
            Me.EmployeesDataTableAdapter.FillByEmpID(Me.TrueTimeDataSet.EmployeesData, SearchLookUpEdit1.EditValue)
        Catch ex As Exception
        End Try


    End Sub



    Private Sub SonNOSpinEdit_EditValueChanged(sender As Object, e As EventArgs) Handles SonNOSpinEdit.EditValueChanged
        If Not IsDBNull(SonNOSpinEdit.EditValue) Then
            If SonNOSpinEdit.EditValue < 0 Then SonNOSpinEdit.EditValue = 0
        End If

    End Sub



    Private Sub DepartmentComboBoxEdit_ProcessNewValue(sender As Object, e As ProcessNewValueEventArgs) Handles DepartmentComboBoxEdit.ProcessNewValue

        If CStr(e.DisplayValue) = String.Empty Then Exit Sub
        Dim Msg As DialogResult = XtraMessageBox.Show("هل تريد اضافة  القسم     : " & e.DisplayValue.ToString(), "تأكيد", MessageBoxButtons.YesNo, MessageBoxIcon.Warning)
        If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub


        Try
            Dim sql As New SQLControl
            Dim SQLString As String
            SQLString = "insert into EmployeesDepartments (Department) values (N'" & e.DisplayValue.ToString() & "')"
            sql.SqlTrueTimeRunQuery(SQLString)
            XtraMessageBox.Show("تم اضافة  القسم ")
            Me.EmployeesDepartmentsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesDepartments)
            e.Handled = True
        Catch ex As Exception
            XtraMessageBox.Show(" خطا: لم يتم  اضافة   القسم ")
            Exit Sub
        End Try

    End Sub



    Private Sub JobNameComboBoxEdit_ProcessNewValue(sender As Object, e As ProcessNewValueEventArgs) Handles JobNameComboBoxEdit.ProcessNewValue
        If CStr(e.DisplayValue) = String.Empty Then Exit Sub
        Dim Msg As DialogResult = XtraMessageBox.Show("هل تريد اضافة مسمى وظيفي   : " & e.DisplayValue.ToString(), "تأكيد", MessageBoxButtons.YesNo, MessageBoxIcon.Warning)
        If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub
        Try
            Dim sql As New SQLControl
            Dim SQLString As String
            SQLString = "insert into EmployeesPositions (Positions) values (N'" & e.DisplayValue.ToString() & "')"
            sql.SqlTrueTimeRunQuery(SQLString)
            XtraMessageBox.Show("تم اضافة المسمى الوظيفي ")
            Me.EmployeesPositionsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesPositions)
            e.Handled = True
        Catch ex As Exception
            XtraMessageBox.Show(" خطا: لم يتم  اضافة المسمى الوظيفي الجديد ")
            Exit Sub
        End Try
    End Sub





    Private Sub BranchComboBoxEdit_ProcessNewValue(sender As Object, e As ProcessNewValueEventArgs) Handles BranchComboBoxEdit.ProcessNewValue

        If CStr(e.DisplayValue) = String.Empty Then Exit Sub
        Dim Msg As DialogResult = XtraMessageBox.Show("هل تريد اضافة الفرع : " & e.DisplayValue.ToString(), "تأكيد", MessageBoxButtons.YesNo, MessageBoxIcon.Warning)
        If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub


        Try
            Dim sql As New SQLControl
            Dim SQLString As String
            SQLString = "insert into EmployeesBranches (Branch) values (N'" & e.DisplayValue.ToString() & "')"
            sql.SqlTrueTimeRunQuery(SQLString)
            XtraMessageBox.Show("تم اضافة الفرع ")
            Me.EmployeesBranchesTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesBranches)
            e.Handled = True
        Catch ex As Exception
            XtraMessageBox.Show(" خطا: لم يتم  اضافة الفرع ")
            Exit Sub
        End Try

    End Sub



    'Private Sub SearchLookUpPlane_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLookUpPlane.EditValueChanged
    '    Try
    '        GridControl1.DataSource = String.Empty
    '        If CStr(EmployeeIDTextEdit.EditValue) = String.Empty Or EmployeeIDTextEdit.EditValue Is Nothing Then Exit Sub

    '        If CStr(SearchLookUpPlane.EditValue) = String.Empty Or SearchLookUpPlane.EditValue Is Nothing Then
    '            XtraMessageBox.Show("لا يوجد وردية")
    '            Exit Sub
    '        End If


    '        Dim sql As New SQLControl
    '        Dim SQLString As Integer = SearchLookUpPlane.EditValue
    '        sql.SqlTrueTimeRunQuery("Select * from AttPlane where PlaneID = " & SQLString)
    '        If sql.SQLDS.Tables.Count = 0 Then Exit Sub
    '        GridControl1.DataSource = sql.SQLDS.Tables(0)

    '    Catch ex As Exception
    '        '   MsgBox(ex.ToString)
    '        '   Exit Sub
    '    End Try
    ' End Sub

    Private Sub SearchLookUpEdit1_AddNewValue(sender As Object, e As AddNewValueEventArgs) Handles SearchLookUpEdit1.AddNewValue
        ClearingEditEmployeeForm()
        EmployeeIDTextEdit.Select()
    End Sub

    Private Sub SimpleButton9_Click(sender As Object, e As EventArgs)
        Lists2.Show()
    End Sub

    'Private Sub SearchLookUpPlane_BeforePopup(sender As Object, e As EventArgs) Handles SearchLookUpPlane.BeforePopup
    '    'Me.AttPlaneDurationTableAdapter.Fill(Me.TrueTimeDataSet.AttPlaneDuration)
    'End Sub

    Private Sub SimpleButton10_Click(sender As Object, e As EventArgs)
        '      AttShiftsPlane.Show()
    End Sub




    Private Sub SimpleButton4_Click_1(sender As Object, e As EventArgs)
        DeleteData()
    End Sub

    Private Sub IDTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles IDTextEdit.EditValueChanged

    End Sub

    Private Sub EmployeeIDTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles EmployeeIDTextEdit.EditValueChanged

        LoadingAttachments(EmployeeIDTextEdit.Text)
        '  BackgroundWorker1.WorkerSupportsCancellation = True
        '  If Not BackgroundWorker1.IsBusy Then BackgroundWorker1.RunWorkerAsync()


        '   CalcTotalVocations()
        'Try
        '    If EmployeeIDTextEdit.Text <> "" Then
        '        Me.EmployeesOhdahTableAdapter.FillByEmpNo(Me.TrueTimeDataSet.EmployeesOhdah, EmployeeIDTextEdit.Text)
        '    End If

        'Catch ex As Exception

        'End Try
        Try
            If EmployeeIDTextEdit.Text <> "" Then
                Me.EmployeesOhdahTableAdapter.FillByEmpNo(Me.TrueTimeDataSet.EmployeesOhdah, EmployeeIDTextEdit.Text)
            End If

        Catch ex As Exception

        End Try

        If Me.EmployeeNameTextEdit.Text <> "" Then GetOtherDetails()

    End Sub
    Private Sub GetOtherDetails()
        Try
            Dim SqlString As String
            Dim Sql As New SQLControl
            SqlString = "SELECT BonusPerHourAmount, BonusPerHourAmountOption, PictureEmp, 
                                ISNULL([AccessOnLogIn], 0) AS AccessOnLogIn,
                                ISNULL([CalAbsentInSalary], 1) AS [CalAbsentInSalary],
                                ISNULL(CalcBonusAfterMinutesInReqHoures, 0) AS CalcBonusAfterMinutesInReqHoures,
                                ManagerIDForWeb, ISNULL(SalaryPerDay, 0) AS SalaryPerDay,
                                ISNULL(RequiredHoursPlane, '') AS RequiredHoursPlane,
                                ISNULL(ActiveSavingFund, 0) AS ActiveSavingFund,
                                ISNULL(SectionsID, 0) AS SectionID,
                                ISNULL(AllowAddCustomerFromApp, 0) AS AllowAddCustomerFromApp,
                                UniversitySonNo,
                                IsNull(AllowAddAttTrans,1) As AllowAddAttTrans,
                                ISNULL(CanEditPrice, 0) AS AllowEditPrice,
                                ISNULL(ShowSalesinvoice, 0) AS AllowShowSalesinvoice,
                                ISNULL(ReceiptVoucher, 0) AS AllowCreateReceiptVoucher
                         FROM [dbo].[EmployeesData]
                         WHERE [EmployeeID] = '" & EmployeeIDTextEdit.Text & "'"
            Sql.SqlTrueTimeRunQuery(SqlString)
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("BonusPerHourAmount")) Then
                BonusPerHourAmountTextEdit.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("BonusPerHourAmount")
            End If
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("BonusPerHourAmountOption")) Then
                BonusPerHourAmountOption.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("BonusPerHourAmountOption")
                '   LayoutControlItem67.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
            Else
                BonusPerHourAmountOption.EditValue = False
            End If
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("AccessOnLogIn")) Then
                AccessOnLogInCheckEdit.EditValue = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("AccessOnLogIn"))
                '   LayoutControlItem67.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
            Else
                BonusPerHourAmountOption.EditValue = False
            End If
            Me.PictureEmpPictureEdit.Image = Nothing
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("PictureEmp")) Then
                Dim photo_aray As Byte()
                photo_aray = CType(Sql.SQLDS.Tables(0).Rows(0).Item("PictureEmp"), Byte())
                Dim ms As MemoryStream = New MemoryStream(photo_aray)
                PictureEmpPictureEdit.Image = Image.FromStream(ms)
            End If
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("CalcBonusAfterMinutesInReqHoures")) Then
                txtInReqHouresCalcBonusAfter.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("CalcBonusAfterMinutesInReqHoures")
            End If
            CheckCalAbsentInSalary.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("CalAbsentInSalary"))
            ActiveSavingFundCheckEdit.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("ActiveSavingFund"))
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("ManagerIDForWeb")) Then
                SearchManagerIDForweb.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("ManagerIDForWeb")
            End If
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("SalaryPerDay")) Then
                txtSalaryPerDay.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("SalaryPerDay")
            End If
            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("SectionID")) Then
                SearchSections.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("SectionID")
            End If
            SearchRequiredPlans.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("RequiredHoursPlane")

            AllowAddCustomerFromApp.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("AllowAddCustomerFromApp"))
            CheckAllowAddAttTrans.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("AllowAddAttTrans"))
            CheckCalAbsentInSalary.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("CalAbsentInSalary"))

            AllowEditPrice.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("AllowEditPrice"))
            AllowShowSalesinvoice.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("AllowShowSalesinvoice"))
            AllowCreateReceiptVoucher.Checked = CBool(Sql.SQLDS.Tables(0).Rows(0).Item("AllowCreateReceiptVoucher"))

            If Not IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("UniversitySonNo")) Then
                TextExemptionsStudents.EditValue = Sql.SQLDS.Tables(0).Rows(0).Item("UniversitySonNo")
            End If

        Catch ex As Exception
            BonusPerHourAmountTextEdit.EditValue = 0
        End Try

        If BonusPerHourAmountOption.EditValue = False Then
            LayoutControlItem67.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
        End If

    End Sub
    Private Sub SimpleButton2_Click_1(sender As Object, e As EventArgs)

    End Sub

    Private Sub VocationsLimitTextEdit_EditValueChanged(sender As Object, e As EventArgs)
        '  CalcTotalVocations()
    End Sub

    Private Sub CalcTotalVocations()


        Try
            Dim _EmployeeID As String
            _EmployeeID = EmployeeIDTextEdit.Text
            If String.IsNullOrEmpty(_EmployeeID) Then Exit Sub

            Dim Sql As New SQLControl
            Dim SQlString As String = " Select VocID,Vocation,ISNULL( VocationPaid,0) as VocationPaid ,isnull(DefaultBalanceForEmployee,0) as DefaultBalanceForEmployee,isnull(IDD,0) As IDD,
                                            '' as Balance, '' as ThisYearVocations,'' as ThisYearSetBalance,'' as BeginingBalance , '' as AccruedVocations 
                                        FROM
                                         (  
			                                 (Select E.VocID,E.Vocation,E.VocationPaid   From VocationsTypes E ) SS
	                                      Left Join
			                                 (Select C.DefaultBalanceForEmployee,C.VocID As VVocID ,C.EmployeeID,C.ID as IDD   From [VocationsDefaultBalances] C where C.EmployeeID=" & _EmployeeID & "  ) DSA		       
	                                      On SS.VocID = DSA.VVocID
                                          ) Order by VocID "

            Sql.SqlTrueTimeRunQuery(SQlString)

            GridControl3.DataSource = Sql.SQLDS.Tables(0)

            Dim VocID As Integer = 0
            For i = 0 To BandedGridView1.RowCount - 1
                VocID = CInt(Me.BandedGridView1.GetRowCellValue(i, "VocID"))
                If Not String.IsNullOrEmpty(VocID) Then
                    Dim _VocationDetails = GetVocationsBalancesByEmployee(_EmployeeID, VocID, Today())
                    BandedGridView1.SetRowCellValue(i, BandedGridView1.Columns("Balance"), _VocationDetails.Balance)
                    BandedGridView1.SetRowCellValue(i, BandedGridView1.Columns("ThisYearVocations"), _VocationDetails.ThisYearVocations)
                    BandedGridView1.SetRowCellValue(i, BandedGridView1.Columns("ThisYearSetBalance"), _VocationDetails.ThisYearSetBalance)
                    BandedGridView1.SetRowCellValue(i, BandedGridView1.Columns("BeginingBalance"), _VocationDetails.BeginingBalance)
                    BandedGridView1.SetRowCellValue(i, BandedGridView1.Columns("AccruedVocations"), _VocationDetails.AccruedVocations)
                End If
            Next
            BandedGridView1.BestFitColumns()

            '  Me.VocationTotalText.Text = CDec(GetVocationDataByEmpID(_EmployeeID).Item1)
            '  Me.VocationCurrentText.Text = CDec(GetVocationDataByEmpID(_EmployeeID).Item2)
            ' Me.AddingCurrentText.Text = CDec(GetVocationDataByEmpID(_EmployeeID).Item3)
            ' Me.VocationBeginingBalanceTextEdit.Text = CDec(GetVocationDataByEmpID(_EmployeeID).Item4)
            ' AccruedVocations.Text = CDec(GetVocationDataByEmpID(_EmployeeID).Item5)

            '  VocationTotalText.EditValue = VocationBeginingBalanceTextEdit.EditValue + VocationsLimitTextEdit.EditValue - VocationCurrentText.EditValue
            '    VocationTotalText.Text = GetVocationsBalanceByEmployee(EmployeeIDTextEdit.Text)
            '   AddingCurrentText.Text = GetSumAddingThisYear(EmployeeIDTextEdit.Text)
            '  Me.VocationTotalText.Text = GetVocationDataByEmpID(2).Item1
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub VocationBeginingBalanceTextEdit_EditValueChanged(sender As Object, e As EventArgs)
        '  CalcTotalVocations()
    End Sub

    Private Function GetSumVocationsThisYear() As String
        Dim sql As New SQLControl
        GetSumVocationsThisYear = 0
        Dim EmpID As String = EmployeeIDTextEdit.Text

        Try
            If EmpID IsNot Nothing And EmpID <> String.Empty And Not IsDBNull(EmpID) Then
                Dim SqlString As String = "Select Sum(NoDays) as SumDays from Vocations where EmployeeID =  " & EmpID &
                    " and VocationType='سنوية' and year(FromDate) = '" & Today.Year.ToString & "'"
                sql.SqlTrueTimeRunQuery(SqlString)

                If sql.SQLDS.Tables(0).Rows(0).Item("SumDays") Is DBNull.Value Then
                    GetSumVocationsThisYear = 0
                Else
                    GetSumVocationsThisYear = sql.SQLDS.Tables(0).Rows(0).Item("SumDays").ToString
                End If



            End If

        Catch ex As Exception
            GetSumVocationsThisYear = 0
        End Try

    End Function



    Private Sub ActiveCheckEdit_CheckedChanged(sender As Object, e As EventArgs) Handles ActiveCheckEdit.EditValueChanged
        If ActiveCheckEdit.Checked = True Then
            ActiveCheckEdit.BackColor = Color.Green
            ActiveCheckEdit.Text = "فعال"
        Else
            ActiveCheckEdit.BackColor = Color.Red
            ActiveCheckEdit.Text = "غير فعال"
        End If
    End Sub

    Private Sub DontCheckInOutCheckEdit_CheckedChanged(sender As Object, e As EventArgs) Handles DontCheckInOutCheckEdit.CheckedChanged
        If DontCheckInOutCheckEdit.Checked = True Then DontCheckInOutCheckEdit.BackColor = Color.Red Else DontCheckInOutCheckEdit.BackColor = Color.Green
    End Sub

    Private Sub BranchComboBoxEdit_Popup(sender As Object, e As EventArgs) Handles BranchComboBoxEdit.BeforePopup
        Me.EmployeesBranchesTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesBranches)
    End Sub

    Private Sub JobNameComboBoxEdit_EditValueChanged(sender As Object, e As EventArgs) Handles JobNameComboBoxEdit.BeforePopup
        Me.EmployeesPositionsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesPositions)
    End Sub

    Private Sub DepartmentComboBoxEdit_EditValueChanged(sender As Object, e As EventArgs) Handles DepartmentComboBoxEdit.BeforePopup
        Me.EmployeesDepartmentsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesDepartments)
    End Sub
    Private Sub Location_EditValueChanged(sender As Object, e As EventArgs) Handles LocationTextEdit.BeforePopup
        Me.LocationsTableAdapter.Fill(Me.TrueTimeDataSet.Locations)
    End Sub

    Private Sub LabelControl8_Click(sender As Object, e As EventArgs)

    End Sub
    Private Sub LoadingAttachments(EmployeeID As String)

        Try
            Dim SQl As New SQLControl
            Dim SqlString As String = " SELECT  [DocID],[DocName],[DocInputUser],[DocSort2],
                                                [DocDetails],[DocType],[DocStatus],[DocInputDate],
                                                [DocExpireDate],[DocCreatedDate],[DocNo],E.[EmployeeName],A.[EmployeeID] ,S.ArchiveDocsSorts1 as DocSort1
                                        FROM [ArchiveDocs] A
                                             left join EmployeesData E on A.EmployeeID = E.EmployeeID 
                                             left join ArchiveDocsSorts1 S on S.ID=A.DocSort1
                                        where A.EmployeeID = '" & EmployeeID & "'  "
            SQl.SqlTrueTimeRunQuery(SqlString)
            GridControl2.DataSource = SQl.SQLDS.Tables(0)
            GridView2.BestFitColumns()
        Catch ex As Exception
            MsgBox(ex.ToString)
            GridControl2.DataSource = Nothing
        End Try


    End Sub

    Private Sub RepositoryOpenFile_ButtonClick(sender As Object, e As ButtonPressedEventArgs) Handles RepositoryOpenFile.ButtonClick
        Dim File As String = CType(Me.GridView3.GetRowCellValue(GridView3.FocusedRowHandle, "DocID"), String)
        'LoadPdfFile(File)
        'Dim mydialogbox As New AttachmentDispaly
        'AttachmentDispaly.ShowDialog()
        OpenAttachment(File)
    End Sub
    Private Sub EmployeeNameTextEdit_Leave(sender As Object, e As EventArgs) Handles EmployeeNameTextEdit.Leave
        If String.IsNullOrEmpty(EmployeeNameTextEdit.Text) Then
            'XtraMessageBox.Show("خطا: الاسم فارغ")
        Else
            IndentyTextEdit.Select()
        End If
    End Sub

    Private Sub PrintVocationsTable_Click(sender As Object, e As EventArgs) Handles PrintVocationsTable.Click
        GridControl3.ShowPrintPreview()
    End Sub
    Private Sub FillWeekDays()
        Dim WeekDaysTable As New DataTable
        With WeekDaysTable
            .Columns.Add("Day")
            .Rows.Add("Saturday")
            .Rows.Add("Sunday")
            .Rows.Add("Monday")
            .Rows.Add("Tuesday")
            .Rows.Add("Wednesday")
            .Rows.Add("Thursday")
            .Rows.Add("Friday")
            '   .Rows.Add("بلا")
        End With
        OffDay1TextEdit.Properties.DataSource = WeekDaysTable
        OffDay2TextEdit.Properties.DataSource = WeekDaysTable

    End Sub

    Private Sub OffDay1TextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles OffDay1TextEdit.EditValueChanged

    End Sub

    Private Sub OffDay1TextEdit_QueryPopUp(sender As Object, e As CancelEventArgs) Handles OffDay1TextEdit.QueryPopUp, OffDay2TextEdit.QueryPopUp
        FillWeekDays()
    End Sub
    Private Sub GetAccess_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        'If CheckIfFormExist(Me.Name) = False Or HasAccessOnForm(Me.Name, "QueryAccess") = False Then
        '    Me.Close()
        '    MsgBox("لا يوجد صلاحية")
        'End If
    End Sub

    Private Function CheckIfFoundInTrueAccounting(SalaryAccountNo As String) As Boolean
        If String.IsNullOrEmpty(SalaryAccountNo) Then
            Return False
            Exit Function
        End If
        Try
            Dim Sql As New SQLControl
            Sql.SqlTrueAccountingRunQuery("select RefNo from Referencess where RefNo = " & SalaryAccountNo)
            If Sql.SQLDS.Tables(0).Rows.Count > 0 Then
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Return False
        End Try
    End Function

    Private Sub RequiredDailyHoures2TextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RequiredDailyHoures2TextEdit.EditValueChanged

    End Sub

    Private Sub RestDailyHouresTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles RestDailyHouresTextEdit.EditValueChanged

    End Sub

    Private Sub EmployeesEdit_Closing(sender As Object, e As CancelEventArgs) Handles Me.Closing
        Me.Dispose()
    End Sub

    Private Sub GridView7_InitNewRow(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.InitNewRowEventArgs) Handles GridView7.InitNewRow

        ' GridView2.SetRowCellValue(e.RowHandle, "DebitCredAcc", GetDefaultAccounts(1, DocCurrencyForReferanceAcc.EditValue, GlobalVariables.CurrUser))
        ' Me.GridView2.SetRowCellValue(e.RowHandle, "ExchangePrice", ExchangePriceForReferanceAcc.EditValue)
        GridView7.SetRowCellValue(e.RowHandle, "OnDate", Format(Today, "yyyy-MM-dd"))
        GridView7.SetRowCellValue(e.RowHandle, "EmployeeNo", EmployeeIDTextEdit.EditValue)
    End Sub
    Private Sub EmployeesOhdahGridControl_ProcessGridKey(ByVal sender As Object, ByVal e As KeyEventArgs) Handles EmployeesOhdahGridControl.ProcessGridKey
        Dim grid = TryCast(sender, GridControl)
        Dim view = TryCast(grid.FocusedView, GridView)
        If e.KeyData = Keys.Delete Then
            view.DeleteSelectedRows()
            view.UpdateSummary()
            e.Handled = True
        End If
    End Sub

    Private Sub JobNameComboBoxEdit_EditValueChanged_1(sender As Object, e As EventArgs) Handles JobNameComboBoxEdit.EditValueChanged

    End Sub

    Private Sub SimpleButton2_Click_2(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        EmployeesOhdahGridControl.ShowPrintPreview()
    End Sub
    Private Sub AdvBandedGridView1_PrintInitialize(sender As System.Object, e As DevExpress.XtraGrid.Views.Base.PrintInitializeEventArgs) Handles GridView7.PrintInitialize

        Dim pb As PrintingSystemBase = CType(e.PrintingSystem, PrintingSystemBase)
        pb.PageSettings.Landscape = True
        pb.PageSettings.LeftMargin = 0
        pb.PageSettings.RightMargin = 0
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Clear()
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Footer.Content.Clear()

        Dim sql As New SQLControl
        Dim SQLString As String = "Select *  from CompanyData"
        sql.SqlTrueTimeRunQuery(SQLString)

        If sql.SQLDS.Tables(0).Rows.Count = 0 Then Exit Sub
        Dim ComName As String = sql.SQLDS.Tables(0).Rows(0).Item("CompanyName")
        Dim Tawqe3 As String = " .................:توقيع الادارة"
        Dim Tawqe3_2 As String = " .................:توقيع الموظف"

        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Footer.Content.AddRange(New String() {Tawqe3, Tawqe3_2, "Pages: [Page # of Pages #]"})
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Footer.Content.Add(Tawqe3)


        If EmployeeNameTextEdit.Text <> String.Empty Or IsDBNull(EmployeeNameTextEdit.EditValue) Or CStr(EmployeeNameTextEdit.EditValue) IsNot Nothing Or CStr(EmployeeNameTextEdit.EditValue) <> "0" Then
            TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Add("عهدة موظف : " & EmployeeNameTextEdit.Text)
        Else
            TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Add("عهدة موظف  ")
        End If

        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Add(ComName)



    End Sub

    Private Sub GridControl2_Click(sender As Object, e As EventArgs) Handles GridControl2.Click

    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        LoadingAttachments(EmployeeIDTextEdit.EditValue)
    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        CalcTotalVocations()
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        Try
            If EmployeeIDTextEdit.Text <> "" Then
                Me.EmployeesOhdahTableAdapter.FillByEmpNo(Me.TrueTimeDataSet.EmployeesOhdah, EmployeeIDTextEdit.EditValue)
            End If

        Catch ex As Exception

        End Try
    End Sub
    Private Sub BackgroundWorker1_DoWork(sender As Object, e As DoWorkEventArgs) Handles BackgroundWorker1.DoWork






        '   CalcTotalVocations()
        Try
            If EmployeeIDTextEdit.Text <> "" Then
                Me.EmployeesOhdahTableAdapter.FillByEmpNo(Me.TrueTimeDataSet.EmployeesOhdah, EmployeeIDTextEdit.Text)
            End If

        Catch ex As Exception

        End Try
    End Sub

    Private Sub BonusPerHourAmountOption_CheckedChanged(sender As Object, e As EventArgs) Handles BonusPerHourAmountOption.CheckedChanged
        If BonusPerHourAmountOption.Checked = True Then
            LayoutControlItem67.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
        Else
            LayoutControlItem67.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
        End If
    End Sub

    Private Sub BonusPerHourAmountTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles BonusPerHourAmountTextEdit.EditValueChanged
        Try
            If BonusPerHourAmountTextEdit.EditValue < 0 Then
                MsgBox("الفيمة لا يجب ان تكون اقل من صفر")
            End If
        Catch ex As Exception

        End Try

    End Sub

    Private Sub UserIDInAttFileTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles UserIDInAttFileTextEdit.EditValueChanged

    End Sub

    Private Sub SalaryAccountNo_EditValueChanged(sender As Object, e As EventArgs) Handles SalaryAccountNo.EditValueChanged

    End Sub

    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs)


    End Sub
    Private Function HasAttTrans(_EmployeeID As Integer) As Boolean
        Dim sqlstring As String
        Dim sql As New SQLControl
        sqlstring = " Select count(ID) As Count from [dbo].[AttCHECKINOUT] where [USERID]=" & _EmployeeID
        Try
            sql.SqlTrueTimeRunQuery(sqlstring)
            If sql.SQLDS.Tables(0).Rows(0).Item("Count") > 0 Then
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Return False
        End Try
    End Function
    Private Function HasVocationsTrans(_EmployeeID As Integer) As Boolean
        Dim sqlstring As String
        Dim sql As New SQLControl
        sqlstring = "   select count(VocID) As Count from [dbo].[Vocations] where EmployeeID =" & _EmployeeID
        Try
            sql.SqlTrueTimeRunQuery(sqlstring)
            If sql.SQLDS.Tables(0).Rows(0).Item("Count") > 0 Then
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Return False
        End Try
    End Function
    Private Function HasVacationsBalancesAddingTrans(_EmployeeID As Integer) As Boolean
        Dim sqlstring As String
        Dim sql As New SQLControl
        sqlstring = "   select count(id) as Count from [dbo].[VacationsBalancesAdding] where Employee=" & _EmployeeID
        Try
            sql.SqlTrueTimeRunQuery(sqlstring)
            If sql.SQLDS.Tables(0).Rows(0).Item("Count") > 0 Then
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Return False
        End Try
    End Function

    Private Sub SimpleButton6_Click_1(sender As Object, e As EventArgs) Handles SimpleButton6.Click
        Dim F As New AttachmentsBulkAdd
        With F
            ' .ReferanceID.EditValue = Me.EmployeeIDTextEdit.EditValue
            .ReferanceID.ReadOnly = True
            .SearchAccount.ReadOnly = True
            .LayoutControlItemEmployees.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
            .EmptySpaceEmployees.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
            .LayoutControlItemReferance.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
            .LayoutControlItemAccounts.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
            .SearchLookEmployees.Properties.DataSource = GetEmployeesList()
            .SearchLookEmployees.EditValue = Me.EmployeeIDTextEdit.Text
            .SearchAccount.EditValue = "2102000000"
            If .ShowDialog() <> DialogResult.OK Then
                LoadingAttachments(EmployeeIDTextEdit.Text)
            End If
        End With
    End Sub
    Private Function GetEmployeesList()
        Dim _EmployeesTable As New DataTable
        Try
            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(" Select EmployeeID,EmployeeName from EmployeesData where EmployeeID <> 9999 and  EmployeeID <> 8888  ")
            _EmployeesTable = sql.SQLDS.Tables(0)
        Catch ex As Exception

        End Try
        Return _EmployeesTable
    End Function

    Private Sub ActiveCheckEdit_CheckedChanged_1(sender As Object, e As EventArgs) Handles ActiveCheckEdit.CheckedChanged

    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        ClearingEditEmployeeForm()
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick
        If HasAttTrans(EmployeeIDTextEdit.EditValue) Then
            XtraMessageBox.Show("خطأ: لا يمكن حذف الموظف، يوجد له حركات دوام")
            Exit Sub
        End If
        If HasVocationsTrans(EmployeeIDTextEdit.EditValue) Then
            XtraMessageBox.Show("خطأ: لا يمكن حذف الموظف، يوجد له حركات اجازات")
            Exit Sub
        End If
        If HasVacationsBalancesAddingTrans(EmployeeIDTextEdit.EditValue) Then
            XtraMessageBox.Show("خطأ: لا يمكن حذف الموظف، يوجد له حركات ترصيد اجازات")
            Exit Sub
        End If

        Dim sql As New SQLControl
        If sql.SqlTrueAccountingRunQuery("Delete from [dbo].[EmployeesData] where [EmployeeID]=" & EmployeeIDTextEdit.EditValue) = True Then
            XtraMessageBox.Show("تم حذف الموظف")
        Else
            XtraMessageBox.Show("خطا: لم يتم حذف الموظف")
        End If
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Saving()
    End Sub

    Private Sub UserPasswordTextEdit_EditValueChanged(sender As Object, e As EventArgs) Handles UserPasswordTextEdit.EditValueChanged

    End Sub
    Private Sub changepassword()
        Try
            If UserPasswordTextEdit.Text <> "" Then
                Dim PassText As String = GetCode(UserPasswordTextEdit.Text, UserPasswordTextEdit.Text)
                Dim SqlString As String = "Update EmployeesData set UserPassword ='" & PassText & "' where EmployeeID =" & EmployeeIDTextEdit.Text
                Dim sql As New SQLControl
                sql.SqlTrueTimeRunQuery(SqlString)
            End If
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub AllowUseOrdersAppCheckEdit_CheckedChanged(sender As Object, e As EventArgs) Handles AllowUseOrdersAppCheckEdit.CheckedChanged
        AccessTypeTextEdit.Text = "Admin"
        RepositoryUserAccessType.EditValue = 1
        Me.Validate()
        Me.EmployeesDataBindingSource.EndEdit()
        Me.EmployeesDataBindingSource.CancelEdit()
        Me.TableAdapterManager.UpdateAll(Me.TrueTimeDataSet)
    End Sub

    Private Sub SimpleButton7_Click_1(sender As Object, e As EventArgs)


    End Sub

    Private Sub AccessOnLogInCheckEdit_CheckedChanged(sender As Object, e As EventArgs) Handles AccessOnLogInCheckEdit.CheckedChanged
        If Me.IsHandleCreated = True Then
            If AccessOnLogInCheckEdit.IsHandleCreated Then
                If Me.AccessOnLogInCheckEdit.Checked Then
                    Dim SqlString As String = " Update EmployeesData set AccessOnLogIn =1 where EmployeeID =" & EmployeeIDTextEdit.Text
                    Dim sql As New SQLControl
                    sql.SqlTrueTimeRunQuery(SqlString)
                Else
                    Dim SqlString As String = " Update EmployeesData set AccessOnLogIn =0 where EmployeeID =" & EmployeeIDTextEdit.Text
                    Dim sql As New SQLControl
                    sql.SqlTrueTimeRunQuery(SqlString)
                End If
            End If
        End If
        '   Me.EmployeesDataTableAdapter.FillByEmpID(Me.TrueTimeDataSet.EmployeesData, EmployeeIDTextEdit.Text)
    End Sub

    Private Sub PasswordForAppsTextEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles PasswordForAppsTextEdit1.EditValueChanged

    End Sub

    Private Sub AccessTypeTextEdit_SelectedIndexChanged(sender As Object, e As EventArgs) Handles AccessTypeTextEdit.SelectedIndexChanged

    End Sub

    Private Sub RepositoryUserAccessType_EditValueChanged(sender As Object, e As EventArgs) Handles RepositoryUserAccessType.EditValueChanged

    End Sub

    Private Sub BarButtonItem3_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarDefaultAccounts.ItemClick
        AccessOnLogInCheckEdit.Checked = True
        If AccessOnLogInCheckEdit.Checked = True Then
            Dim F As New DefaultsAccounts
            With F
                .SearchLookUsers.EditValue = EmployeeIDTextEdit.EditValue
                .ShowDialog()
            End With
        Else
            XtraMessageBox.Show(" يرجى تفعيل خاصية الدخول  ")
        End If
    End Sub

    Private Sub SimpleButton7_Click_2(sender As Object, e As EventArgs)
        EmployeesOhdahGridControl.ShowPrintPreview()
    End Sub
    Private _CheckIfChanged As Boolean = True
    Private Sub CheckHR_CheckedChanged(sender As Object, e As EventArgs) Handles CheckHR.CheckedChanged

        Try
            Dim sql As New SQLControl
            Dim sqlstring As String
            If _CheckIfChanged = True Then
                Select Case CheckHR.Checked
                    Case True
                        sqlstring = "  IF EXISTS (SELECT * FROM [EmployeesData] WHERE ApproveInd = 'hr') 
                        SELECT 'True' as result
                       ELSE 
                        SELECT 'False' as result"
                        sql.SqlTrueTimeRunQuery(sqlstring)
                        If sql.SQLDS.Tables(0).Rows(0).Item("result") Then
                            MsgBoxShowError(" يوجد موظف مدير شؤون موظفين من قبل ")
                            _CheckIfChanged = False
                            CheckHR.CheckState = False
                            Exit Sub
                        End If
                    Case False
                        sqlstring = " update [EmployeesData]  set ApproveInd ='no' where [EmployeeID]='" & EmployeeIDTextEdit.Text & "'"
                        sql.SqlTrueAccountingRunQuery(sqlstring)
                        '    _CheckIfChanged = True
                End Select
            End If
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub RadioGroup1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles RadioGroup1.SelectedIndexChanged
        Dim sql As New SQLControl
        Dim sqlstring As String
        Select Case RadioGroup1.EditValue
            Case "yes"
                sqlstring = " update [EmployeesData]  set ApproveInd ='yes' where [EmployeeID]='" & EmployeeIDTextEdit.Text & "'"
                sql.SqlTrueAccountingRunQuery(sqlstring)
            Case "partially"
                sqlstring = " update [EmployeesData]  set ApproveInd ='partially' where [EmployeeID]='" & EmployeeIDTextEdit.Text & "'"
                sql.SqlTrueAccountingRunQuery(sqlstring)
            Case "no"
                sqlstring = " update [EmployeesData]  set ApproveInd ='no' where [EmployeeID]='" & EmployeeIDTextEdit.Text & "'"
                sql.SqlTrueAccountingRunQuery(sqlstring)
        End Select
    End Sub

    Private Sub BarButtonItem3_ItemClick_1(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem3.ItemClick

    End Sub

    Private Sub RadioGroup1_Click(sender As Object, e As EventArgs) Handles RadioGroup1.Click

    End Sub

    Private Sub CheckHR_Click(sender As Object, e As EventArgs) Handles CheckHR.Click

    End Sub

    Private Sub CheckCalAbsentInSalary_CheckedChanged(sender As Object, e As EventArgs) Handles CheckCalAbsentInSalary.CheckedChanged
        Dim sql As New SQLControl
        Dim sqlstring As String

        If CheckCalAbsentInSalary.Checked = True Then
            sqlstring = " Update [EmployeesData] set [CalAbsentInSalary]=1 where [EmployeeID]='" & EmployeeIDTextEdit.Text & "'"
            sql.SqlTrueTimeRunQuery(sqlstring)
        Else
            sqlstring = " Update [EmployeesData] set [CalAbsentInSalary]=0 where [EmployeeID]='" & EmployeeIDTextEdit.Text & "'"
            sql.SqlTrueTimeRunQuery(sqlstring)
        End If
    End Sub

    Private Sub SearchRequiredPlans_EditValueChanged(sender As Object, e As EventArgs) Handles SearchRequiredPlans.EditValueChanged
        If Me.SearchRequiredPlans.Text = "" Then
            LayoutRequiredHours.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
        Else
            LayoutRequiredHours.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
        End If
    End Sub

    Private Sub BarButtonItem4_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem4.ItemClick
        Dim sql As New SQLControl
        Dim sqlString As String = "  Update [dbo].[EmployeesData]   set IsCookieSet=0,Cookie='' where EmployeeID=" & EmployeeIDTextEdit.EditValue
        If sql.SqlTrueTimeRunQuery(sqlString) Then
            MsgBoxShowSuccess(" تم مسح البيانات ")
        End If
    End Sub

    Private Sub SearchSections_Properties_AddNewValue(sender As Object, e As AddNewValueEventArgs) Handles SearchSections.Properties.AddNewValue
        Dim f As New AttEmployeesSections
        With f
            If .ShowDialog <> DialogResult.OK Then
                SearchSections.Properties.DataSource = GetEmployeesSections()
            End If
        End With
    End Sub
End Class