Public Class MainDashBoard
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        '   EmployeesDataTableAdapter1.Fill(TrueTimeDataSet1.EmployeesData)
        ' This line of code is generated by Data Source Configuration Wizard
        'EmployeesDataTableAdapter2.Fill(TrueTimeDataSet2.EmployeesData)
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub TileItem2_ItemClick(sender As Object, e As DevExpress.XtraEditors.TileItemEventArgs) Handles TileItem2.ItemClick
        SettingsForms.Show()
    End Sub

    Private Sub TileItem1_ItemClick(sender As Object, e As DevExpress.XtraEditors.TileItemEventArgs) Handles TileItem1.ItemClick
        EmployeesEdit.Show()
    End Sub

    Private Sub TileItem4_ItemClick(sender As Object, e As DevExpress.XtraEditors.TileItemEventArgs) Handles TileItem4.ItemClick
        ReadClock.Show()
    End Sub

    Private Sub TileItem3_ItemClick(sender As Object, e As DevExpress.XtraEditors.TileItemEventArgs) Handles TileItem3.ItemClick
        'EmployeesCardView.Show()
    End Sub

    Private Sub TileControl1_Click(sender As Object, e As EventArgs) Handles TileControl1.Click

    End Sub
End Class