Imports DevExpress.XtraEditors
Imports DevExpress.XtraEditors.Controls
Imports DevExpress.XtraGrid.Views.Base
Imports System.ComponentModel
Imports System.Data.SqlClient
Imports System.IO

Public Class AttachmentsAdd
    Dim FromShoose As String = "Grid"
    Dim LinkedTable As String, Field1 As String, Field2 As String, Field3 As String, Field4 As String, Field5 As String
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource

    End Sub

    Dim CurrentUser As String = GlobalVariables.CurrUser
    Private Sub ButtonEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles ButtonEditBrowseFile.EditValueChanged
        Try
            Me.PdfViewer1.LoadDocument(Me.ButtonEditBrowseFile.Text)
            Dim information = My.Computer.FileSystem.GetFileInfo(ButtonEditBrowseFile.Text)
            TextDateModified.Text = information.LastWriteTime
            DocType.Text = information.Extension
            DocName.Text = information.Name
        Catch ex As Exception

        End Try
    End Sub

    Private Function GetIFDelete() As String
        Try
            Dim sql As New SQLControl
            Dim SqlString As String = "  select SettingValue from [Settings] where SettingName ='Archive_DeleteDocAfterArchive' "
            sql.SqlTrueTimeRunQuery(SqlString)
            Return CStr(sql.SQLDS.Tables(0).Rows(0).Item("SettingValue"))
        Catch ex As Exception
            Return "0"
        End Try
    End Function


    Private Sub ButtonEdit1_ButtonClick(sender As Object, e As ButtonPressedEventArgs) Handles ButtonEditBrowseFile.ButtonClick
        Try
            XtraOpenFileDialog1.ShowDialog()
            Me.ButtonEditBrowseFile.Text = XtraOpenFileDialog1.FileName
            FromShoose = "Browse"

        Catch ex As Exception

        End Try
    End Sub

    Private Sub AttachmentsAdd_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'TrueTimeDataSet.ArchiveDocsTypes' table. You can move, or remove it, as needed.
        '  Me.ArchiveDocsTypesTableAdapter.Fill(Me.TrueTimeDataSet.ArchiveDocsSorts1)

        LoadingAccountsdata()
        LoadingSorts1()
        MemoEditManual.Text = " اختر الملف من الجدول على يمين الشاسة واملئ الحقول المتعلقة ببيانات الوثيقة على يسار الشاشة ثم اضغط على زر حفظ     "
        Myfolder()
        LoadingLinkedDocs()

    End Sub

    Private Sub Myfolder()
        Try
            Dim SqlString As String = "SELECT [ArchiveFolder]  FROM [EmployeesData] where EmployeeID ='" & CurrentUser & "'"
            Dim Sql As New SQLControl
            Sql.SqlTrueTimeRunQuery(SqlString)
            ButtonEditBrowseFolder.Text = Sql.SQLDS.Tables(0).Rows(0).Item("ArchiveFolder").ToString
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub ButtonEditBrowseFolder_EditValueChanged(sender As Object, e As EventArgs) Handles ButtonEditBrowseFolder.EditValueChanged
        LoadFilesFromFolder()
    End Sub
    Public Sub ProcessDirectoryByFile(ByVal targetDirectory As String)
        Try

        Catch ex As Exception

        End Try
    End Sub
    Public Sub ProcessDirectory(ByVal targetDirectory As String, ByRef dt As DataTable)
        Try
            Dim fileEntries As String() = Directory.GetFiles(targetDirectory)
            For Each fileName As String In fileEntries
                Dim fi As FileInfo = New FileInfo(fileName)
                If fi.Extension = ".pdf" Then
                    dt.Rows.Add(Nothing, fi.Name, targetDirectory, fi.CreationTime, fi.Extension, fi.FullName, fi.LastWriteTime)
                End If
            Next
            Dim subdirectoryEntries As String() = Directory.GetDirectories(targetDirectory)

            For Each subdirectory As String In subdirectoryEntries
                ProcessDirectory(subdirectory, dt)
            Next
        Catch ex As Exception

        End Try
    End Sub

    Private Sub LoadFilesFromFolder()

        Try
            Dim dt As DataTable = New DataTable("Mydata")
            dt.Columns.Add("ID", GetType(Integer))
            dt.Columns.Add("File", GetType(String))
            dt.Columns.Add("Folder", GetType(String))
            dt.Columns.Add("CreationTime", GetType(DateTime))
            dt.Columns.Add("Extension", GetType(String))
            dt.Columns.Add("FullName", GetType(String))
            dt.Columns.Add("LastWriteTime", GetType(String))
            dt.Columns("ID").AutoIncrement = True
            dt.Columns("ID").AutoIncrementSeed = 1
            dt.Columns("ID").AutoIncrementStep = 1
            ProcessDirectory(ButtonEditBrowseFolder.Text.Trim(), dt)
            Dim dataView As New DataView(dt)
            ' dataView.Sort = "  CreationTime DeSC"
            Dim dataTable As DataTable = dataView.ToTable()
            GridControl1.DataSource = dataTable
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try

    End Sub
    Private Sub GridView1_FocusedRowChanged(sender As Object, e As FocusedRowChangedEventArgs) Handles GridView1.FocusedRowChanged
        Try
            Dim File As String = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "FullName"), String)
            ButtonEditBrowseFile.Text = File
            DocType.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "Extension"), String)
            TextDateModified.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "LastWriteTime"), String)
            DocName.Text = CType(Me.GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "File"), String)
            FromShoose = "Grid"
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub Saving()



        Try
            If String.IsNullOrWhiteSpace(DocName.Text) Then
                XtraMessageBox.Show("يجب تعبئة اسم الوثيقة")
                Exit Sub
            End If

            If String.IsNullOrWhiteSpace(DocSort1.Text) Then
                XtraMessageBox.Show("يجب تعبئة تصنيف الوثيقة")
                Exit Sub
            End If

            Dim _DocName As String = DocName.Text
            Dim _DocAccountCode As String = DocAccountCode.EditValue
            Dim _DocInputDate As String = Format(Now, "yyyy-MM-dd HH:mm")
            Dim _DocSort1 As String = DocSort1.Text
            Dim _DocCostCenter As String = DocCostCenter.Text
            Dim _DocDetails As String = DocDetails.Text
            Dim _DocLocation As String = ButtonEditBrowseFile.Text
            Dim _DocType As String = DocType.Text
            Dim _DocExpireDate As String = Format(DocExpireDate.DateTime, "yyyy-MM-dd HH:mm")
            Dim _DocNo As String = DocNo.Text
            Dim _DocCode As String = DocCode.Text
            Dim _TextDateModified As String = Format(CDate(TextDateModified.Text), "yyyy-MM-dd HH:mm")
            Dim _LinkDocType As String = SearchLinkDoc.Text
            Dim _LinkDocNo As String = SearchLinkDocNo.EditValue

            Dim sql As New SQLControl


            Dim file As Byte()
            Using stream = New FileStream(_DocLocation, FileMode.Open, FileAccess.Read)
                Using reader = New BinaryReader(stream)
                    file = reader.ReadBytes(CInt(stream.Length))
                End Using
            End Using

            Dim query As String = String.Empty
            query &= "INSERT INTO ArchiveDocs  (  [DocName],DocAccountCode,DocInputDate,DocInputUser,DocSort1,DocCostCenter,DocDetails,DocLocation,DocFile, DocType,DocExpireDate,DocNo,DocCode,TextDateModified,LinkDocType,LinkDocNo)  "
            query &= "VALUES (@DocName,@DocAccountCode, @DocInputDate, @DocInputUser,@DocSort1, @DocCostCenter,@DocDetails,@DocLocation,@DocFile,@DocType,@DocExpireDate,@DocNo,@DocCode,@TextDateModified,@LinkDocType,@LinkDocNo)"

            Using conn As New SqlConnection(My.Settings.TrueTimeConnectionString)
                Using comm As New SqlCommand()
                    With comm
                        .Connection = conn
                        .CommandType = CommandType.Text
                        .CommandText = query
                        .Parameters.AddWithValue("@DocName", _DocName)
                        .Parameters.AddWithValue("@DocAccountCode", _DocAccountCode)
                        .Parameters.AddWithValue("@DocInputDate", _DocInputDate)
                        .Parameters.AddWithValue("@DocInputUser", CurrentUser)
                        .Parameters.AddWithValue("@DocSort1", _DocSort1)
                        .Parameters.AddWithValue("@DocCostCenter", _DocCostCenter)
                        .Parameters.AddWithValue("@DocDetails", _DocDetails)
                        .Parameters.AddWithValue("@DocLocation", _DocLocation)
                        .Parameters.Add("@DocFile", SqlDbType.VarBinary, file.Length).Value = file
                        .Parameters.AddWithValue("@DocType", _DocType)
                        .Parameters.AddWithValue("@DocExpireDate", _DocExpireDate)
                        .Parameters.AddWithValue("@DocNo", _DocNo)
                        .Parameters.AddWithValue("@DocCode", _DocCode)
                        .Parameters.AddWithValue("@TextDateModified", _TextDateModified)
                        .Parameters.AddWithValue("@LinkDocType", _LinkDocType)
                        .Parameters.AddWithValue("@LinkDocNo", _LinkDocNo)
                    End With
                    conn.Open()
                    comm.ExecuteNonQuery()
                End Using
            End Using


            If FromShoose = "Grid" Then
                GridView1.DeleteRow(GridView1.FocusedRowHandle)
                GridView1.RefreshData()
                ' GridView1.SelectRow()
                ButtonEditBrowseFile.Text = String.Empty
            Else
                ButtonEditBrowseFile.Text = String.Empty
            End If

            PdfViewer1.DocumentFilePath = String.Empty

            Dim focusedRow As Integer = GridView1.FocusedRowHandle

            '   AddHandler GridView1.FocusedRowChanged, AddressOf GridView1_FocusedRowChanged

            If GetIFDelete() = "1" Then
                My.Computer.FileSystem.DeleteFile(_DocLocation)
            End If


            GridView1.SelectRow(focusedRow + 1)
            GridView1.Focus()

            XtraMessageBox.Show("تم حفظ الملف", "حفظ", MessageBoxButtons.OK)

            'AddHandler GridView1.FocusedRowChanged()


        Catch ex As Exception
            XtraMessageBox.Show("خطا في حفظ الملف" & ex.ToString)
        End Try



    End Sub
    Sub CellValueChanging(ByVal sender As Object, ByVal e As CellValueChangedEventArgs)
        AddHandler GridView1.FocusedRowChanged, AddressOf GridView1_FocusedRowChanged
    End Sub
    Private Sub DocSort_QueryPopUp(sender As Object, e As CancelEventArgs) Handles DocSort1.QueryPopUp
        '  Me.ArchiveDocsTypesTableAdapter.Fill(Me.TrueTimeDataSet.ArchiveDocsSorts1)
        LoadingSorts1()
    End Sub

    Private Sub DocAccountCode_QueryPopUp(sender As Object, e As EventArgs) Handles DocAccountCode.QueryPopUp
        LoadingAccountsdata()
    End Sub

    Private Sub LoadingAccountsdata()
        Try
            Dim SQl As New SQLControl
            Dim SqlString As String = " Select EmployeeID as AccID ,EmployeeName As AccName from EmployeesData  "
            SQl.SqlTrueTimeRunQuery(SqlString)
            DocAccountCode.Properties.DataSource = SQl.SQLDS.Tables(0)
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub
    Private Sub LoadingSorts1()
        Try
            Dim SQl As New SQLControl
            Dim SqlString As String = " SELECT  [ArchiveDocsSorts1]  FROM [ArchiveDocsSorts1]  "
            SQl.SqlTrueTimeRunQuery(SqlString)
            DocSort1.Properties.DataSource = SQl.SQLDS.Tables(0)
        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click
        FromShoose = "Grid"
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        LoadFilesFromFolder()

    End Sub

    Private Sub DocSort1_EditValueChanged(sender As Object, e As EventArgs) Handles DocSort1.EditValueChanged

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Saving()
    End Sub

    Private Sub DocAccountCode_EditValueChanged(sender As Object, e As EventArgs) Handles DocAccountCode.QueryPopUp
        LoadingAccountsdata()
    End Sub
    Private Sub LoadingLinkedDocs()
        LinkedTable = String.Empty : Field1 = String.Empty : Field2 = String.Empty : Field3 = String.Empty : Field4 = String.Empty : Field5 = String.Empty
        Try
            Dim SQl As New SQLControl
            Dim SqlString As String = " Select [ID] ,FormName ,FormNameArabic,LinkedTable,Field1,Field2,Field3,Field4,Field5 from AccessForms   where DisplayForArchive=1 "
            SQl.SqlTrueTimeRunQuery(SqlString)
            SearchLinkDoc.Properties.DataSource = SQl.SQLDS.Tables(0)
            LinkedTable = SQl.SQLDS.Tables(0).Rows(0).Item("LinkedTable").ToString
            Field1 = SQl.SQLDS.Tables(0).Rows(0).Item("Field1").ToString
            Field2 = SQl.SQLDS.Tables(0).Rows(0).Item("Field2").ToString
            Field3 = SQl.SQLDS.Tables(0).Rows(0).Item("Field3").ToString
            Field4 = SQl.SQLDS.Tables(0).Rows(0).Item("Field4").ToString
            Field5 = SQl.SQLDS.Tables(0).Rows(0).Item("Field5").ToString
        Catch ex As Exception
            ' MsgBox(ex.ToString)
            MsgBox("خطا في تحميل انواع السندات")
        End Try
    End Sub

    Private Sub SearchLinkDoc_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLinkDoc.QueryPopUp
        LoadingLinkedDocs()
    End Sub
    Private Sub SearchLinkDocNo_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLinkDocNo.QueryPopUp
        LoadingLinkedDocsNo()
    End Sub
    Private Sub LoadingLinkedDocsNo()
        Try
            Dim SQl As New SQLControl
            Dim SqlString As String = " select  " & Field1 & "," & Field2 & "," & Field3 & "," & Field4 & "," & Field5 & " From " & LinkedTable
            SQl.SqlTrueTimeRunQuery(SqlString)
            SearchLinkDocNo.Properties.DataSource = SQl.SQLDS.Tables(0)
            SearchLinkDocNo.Properties.DisplayMember = Field1
            SearchLinkDocNo.Properties.ValueMember = Field1

        Catch ex As Exception
            MsgBox("خطا في تحميل بيانات السند")
            ' MsgBox(ex.ToString)
        End Try
    End Sub

    Private Sub GetAccess_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        If CheckIfFormExist(Me.Name) = False Or HasAccessOnForm(Me.Name, "QueryAccess") = False Then
            Me.Close()
            MsgBox("لا يوجد صلاحية")
        End If
    End Sub
End Class