Public Class PosItemsSaleReport
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard

    End Sub
    Private Sub AddVocation_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F5 Then
            RefreshData()
        End If
    End Sub
    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        RefreshData()
    End Sub
    Private Sub RefreshData()
        Try
            'LayoutControlGroupPivotTable.Selected = True
            TabbedControlGroup1.SelectedTabPage = LayoutControlGroupPivotTable
            Dim Sql As New SQLControl
            Dim _DateFrom, _DateTo As String
            _DateFrom = Format(DateEditFrom.DateTime, "yyyy-MM-dd HH:mm:ss")
            _DateTo = Format(DateEditTo.DateTime, "yyyy-MM-dd HH:mm:ss")
            Dim SqlString As String
            SqlString = " Select [DocID],[DocDate],[DocName],Case when J.Docname=2 then [BaseCurrAmount] when J.DocName=12 then -BaseCurrAmount end as BaseCurrAmount,C.[CategoryName],T.[TradeMarkName],G.[GroupName],
                                      [BaseCurrAmount],J.[InputDateTime],[StockID],U.[name] as UnitName,
                                      Case when J.Docname=2 then [StockQuantity] when J.DocName=12 then -1 * StockQuantity end as StockQuantity ,[StockDiscount],[DocCode],I.[ItemName],[ShiftID],
                                      [DocNoteByAccount],[StockBarcode],J.[PosNo],P2.POSName,[DeviceName],[Color],
                                      [Measure],[VoucherDiscount],[ItemVAT],[StockDebitShelve],[StockCreditShelve],
                                      IsNull(I.[LastPurchasePrice],0) As LastPurchasePrice,(BaseCurrAmount-IsNull(I.[LastPurchasePrice],0))  As ProfitMargine,TB.TableName,J.InputUser
                              from journal J
        left join Items I on J.StockID=I.ItemNo
        left Join Units U on J.StockUnit=U.id
        left join [ItemsCategories] C on C.[CategoryID]=I.CategoryID
        left join [ItemsTradeMark] T on T.[TradeMarkID]=I.TradeMarkID
        left join [ItemsGroups] G on G.[GroupID]=I.GroupID
        Left join [PosTables] TB on TB.TableID =J.TableID
        Left join AccountingPOSNames P2 on P2.ID = J.PosNo
        where DocName in (2,12) And [ShiftID]  Is Not Null And J.StockID <>0 and J.StockID is not null And J.InputDateTime Between'" & _DateFrom & "' And '" & _DateTo & "' 
        "
            If SearchPOSNames.EditValue IsNot Nothing Then
                SqlString += " And J.PosNo ='" & SearchPOSNames.EditValue & "'"
                ColPOSName.Visible = True
            End If
            SqlString += "  Order By J.[InputDateTime] "
            Sql.SqlTrueAccountingRunQuery(SqlString)
            GridControl1.DataSource = Sql.SQLDS.Tables(0)

            SqlString = " Select Sum(Case when J.Docname=2 then [BaseCurrAmount] when J.DocName=12 then -1 * BaseCurrAmount end)  as BaseCurrAmount 
               ,Sum(Case when J.Docname=2 then [StockQuantity] when J.DocName=12 then -1 * StockQuantity end)  as StockQuantity ,Sum([StockDiscount]) as StockDiscount ,
               IsNull(Sum([VoucherDiscount]),0) as [VoucherDiscount],I.[ItemName],[StockID],P2.POSName, C.[CategoryName],T.[TradeMarkName],G.[GroupName]
                from journal J
                        left join Items I on J.StockID=I.ItemNo
                        left Join Units U on J.StockUnit=U.id
                        left join [ItemsCategories] C on C.[CategoryID]=I.CategoryID
                        left join [ItemsTradeMark] T on T.[TradeMarkID]=I.TradeMarkID
                        left join [ItemsGroups] G on G.[GroupID]=I.GroupID
                        Left join AccountingPOSNames P2 on P2.ID = J.PosNo
                where DocName in (2,12) And [ShiftID]  Is Not Null And J.StockID <>0 and J.StockID is not null And J.InputDateTime Between'" & _DateFrom & "' And '" & _DateTo & "'"
            If SearchPOSNames.EditValue IsNot Nothing Then
                SqlString += " And J.PosNo ='" & SearchPOSNames.EditValue & "'"
                ColPOSName.Visible = True
            End If
            SqlString += " group by I.[ItemName],[StockID], C.[CategoryName],T.[TradeMarkName],G.[GroupName],P2.POSName Order By StockID "
            Sql.SqlTrueAccountingRunQuery(SqlString)
            GridControl2.DataSource = Sql.SQLDS.Tables(0)
            PivotGridControl1.DataSource = Sql.SQLDS.Tables(0)
            TabbedControlGroup1.SelectedTabPage = LayoutControlGroup2
        Catch ex As Exception
            MsgBoxShowError(ex.ToString)
        End Try

    End Sub

    Private Sub PosItemsSaleReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.DateEditTo.DateTime = Today() & " 23:59:59"
        Dim startDt As New Date(Today.Year, Today.Month, 1)
        Me.DateEditFrom.DateTime = startDt
        'TODO: This line of code loads data into the 'ShalashForTestDataSet.Journal' table. You can move, or remove it, as needed.
        'Me.JournalTableAdapter.Fill(Me.ShalashForTestDataSet.Journal)
        'SqlDataSource1.Fill()
        Me.KeyPreview = True
        TabbedControlGroup1.SelectedTabPage = LayoutControlGroup2
        Me.SearchPOSNames.Properties.DataSource = GetAccountingPosNamesTable()
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        GridView1.OptionsSelection.MultiSelect = True
        GridView1.SelectAll()
        GridView1.CopyToClipboard()
        GridView1.OptionsSelection.MultiSelect = False
    End Sub

    'Async Sub FillDataSourceAsyncAllQueries()
    '    Await SqlDataSource1.FillAsync()
    'End Sub
End Class