Imports DevExpress.XtraCharts

Public Class AccountsMonthlyPivot
    Dim _ShowChart As Boolean = False
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill the SqlDataSource
        SqlDataSource1.Fill()
    End Sub

    Private Sub AccountsMonthlyPivot_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        PivotGridControl1.Prefilter.CriteriaString = "[" + fieldStatmentName.PrefilterColumnName +
                "]== 'قائمة دخل' "
        LayoutChart.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
        PivotGridControl1.BestFitColumnArea()





    End Sub

    Private Sub عرضالرسمالبيانيToolStripMenuItem_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick



        ' seriesLabel.TextPattern = "{V:F1}"

        If _ShowChart = False Then
            LayoutChart.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
            ChartControl1.SeriesTemplate.LabelsVisibility = True
            ChartControl1.CrosshairEnabled = True
            _ShowChart = True
        Else
            LayoutChart.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
            ChartControl1.SeriesTemplate.LabelsVisibility = True
            ChartControl1.CrosshairEnabled = True
            _ShowChart = False
        End If



    End Sub

    Private Sub PivotGridControl1_Click(sender As Object, e As EventArgs) Handles PivotGridControl1.CustomChartDataSourceRows
        Try
            Dim S As Integer = ChartControl1.Series.Count
            For i = 0 To S - 1
                ChartControl1.Series(i).LabelsVisibility = DevExpress.Utils.DefaultBoolean.[True]
                Dim seriesLabel As BarSeriesLabel = TryCast(ChartControl1.Series(i).Label, BarSeriesLabel)
                seriesLabel.BackColor = Color.White
                seriesLabel.Border.Color = Color.DarkSlateGray
                seriesLabel.Font = New Font("Tahoma", 10, FontStyle.Regular)
                seriesLabel.Position = BarSeriesLabelPosition.TopInside
                seriesLabel.TextOrientation = TextOrientation.Horizontal

            Next
        Catch ex As Exception

        End Try
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick
        Dim pivotExportOptions As New DevExpress.XtraPivotGrid.PivotXlsxExportOptions()
        pivotExportOptions.ExportType = DevExpress.Export.ExportType.WYSIWYG
        PivotGridControl1.ExportToXlsx("pivot.xlsx", pivotExportOptions)
    End Sub

    Private Sub BarButtonItem3_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem3.ItemClick
        PivotGridControl1.ShowPrintPreview()
    End Sub
End Class