Imports DevExpress.Utils
Imports DevExpress.XtraEditors
Imports DevExpress.XtraGrid
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraGrid.Views.Grid.ViewInfo
Imports DevExpress.XtraPrinting
Imports DevExpress.XtraReports.ReportGeneration
Imports DevExpress.XtraReports.UI
Imports DevExpress.XtraSplashScreen
Imports System.Data.SqlClient
Imports System.Data.SqlTypes
Imports System.Drawing

Public Class SalaryPosted
    Dim _ShowChart As Boolean = False
    Private _Mode As String
    Private _Image As Image
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource


        ' loadBrancehs()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        'SqlDataSource2.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '  SqlDataSource3.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '  SqlDataSource4.Fill()
        '  LoadEmployees()

        Dim _Month, _Year As Integer
        If Today.Month = 1 Then
            _Month = 12
            _Year = Today.Year - 1
        Else
            _Month = Today.Month - 1
            _Year = Today.Year
        End If


        Dim startDt As New Date(_Year, _Month, 1)
        Dim EndDt As New Date(_Year, _Month, System.DateTime.DaysInMonth(_Year, _Month))

        Me.DateEditFrom.DateTime = startDt
        Me.DateEditTo.DateTime = EndDt
        CheckDataFromEmpData.Checked = True
        CheckDataFromEmpData.Checked = False

        Me.RepositoryProcessType.DataSource = CreatPreccessTypeTable()

        LoadingSalaryPosted()


    End Sub
    Private Sub SalaryPosted_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'TrueTimeDataSet.EmployeesData1' table. You can move, or remove it, as needed.
        '  Me.EmployeesData1TableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData1)
        BandedGridView1.OptionsView.ColumnAutoWidth = True
        BandedGridView1.OptionsView.ShowPreview = False
        '  CheckDataFromEmpData.Checked = False
        If GlobalVariables._SystemLanguage = "Arabic" Then
            RepositoryArchiveStatus.Columns("StatusName").Visible = True
            RepositoryArchiveStatus.Columns("StatusNameEn").Visible = False
            RepositoryArchiveStatus.DisplayMember = "StatusName"
        Else
            RepositoryArchiveStatus.Columns("StatusName").Visible = False
            RepositoryArchiveStatus.Columns("StatusNameEn").Visible = True
            RepositoryArchiveStatus.DisplayMember = "StatusNameEn"
        End If
        RepositoryArchiveStatus.DataSource = GetArchiveStatus()

        Try
            Dim SqlString As String
            Dim sql As New SQLControl
            SqlString = " select SettingValue From Settings where SettingName ='TempForOpenForms'"
            sql.SqlTrueTimeRunQuery(SqlString)
            _Mode = sql.SQLDS.Tables(0).Rows(0).Item("SettingValue")
        Catch ex As Exception
            _Mode = "0"
            XtraMessageBox.Show(ex.ToString)
        End Try


        Select Case _Mode
            Case "Attendance"
                gridBandSalary.Visible = False
                gridBandAttendance.Visible = True
                LayoutControlGroupPivot.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
                Me.Text = "كشوفات الدوام"
                BarButtonItemPrintSalaryDocument.Visibility = DevExpress.XtraBars.BarItemVisibility.Never

            Case "Salary"
                gridBandSalary.Visible = True
                gridBandAttendance.Visible = False
                Me.Text = "كشوفات الرواتب"
                LayoutControlGroupPivot.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
                BarButtonItemPrintSalaryDocument.Visibility = DevExpress.XtraBars.BarItemVisibility.Always
        End Select
        'CreateLogo()

        Me.KeyPreview = True

    End Sub
    Private Sub BandedGridView1_CustomDrawCell(ByVal sender As Object, ByVal e As RowCellCustomDrawEventArgs) Handles BandedGridView1.CustomDrawCell
        Dim View As GridView = CType(sender, GridView)
        If e.Column.FieldName = "ArchiveStatus" Then
            Dim category As String = View.GetRowCellDisplayText(e.RowHandle, View.Columns("ArchiveStatus"))
            If category = "محفوظ" Then
                e.DisplayText = String.Format(DocumentsStatus.Saved)
                e.Appearance.Options.CancelUpdate()
            ElseIf category = "مرحل" Then
                e.DisplayText = String.Format(DocumentsStatus.Posted)
                e.Appearance.Options.CancelUpdate()
            ElseIf category = "الي" Then
                e.DisplayText = String.Format(DocumentsStatus.Auto)
                e.Appearance.Options.CancelUpdate()
            End If
        End If

        'Dim category As String = View.GetRowCellDisplayText(e.RowHandle, View.Columns("DocStatus"))
        'e.DisplayText = "Maroon <color=green>Green</color> Maroon"

    End Sub
    Private Sub AddVocation_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F5 Then
            LoadingSalaryPosted()
        End If
        If e.KeyCode = Keys.F2 Then
            PostSalary(False)
        End If
    End Sub
    Function GetArchiveStatus() As DataTable
        Dim table As New DataTable
        table.Columns.Add("ID", GetType(Integer))
        table.Columns.Add("StatusName", GetType(String))
        table.Columns.Add("StatusNameEn", GetType(String))
        table.Rows.Add(0, "محفوظ", "Saved")
        table.Rows.Add(1, "مرحل", "Posted")
        Return table
    End Function

    Private Sub LoadEmployees()
        Try
            Dim sql As New SQLControl
            Dim SqlString As String
            SqlString = " select distinct (EmployeeID),EmployeeName,EmployeeNoAsAcc from [AttRawatebArchive]   "
            sql.SqlTrueTimeRunQuery(SqlString)
            SearchEmployees.Properties.DataSource = sql.SQLDS.Tables(0)
        Catch ex As Exception

        End Try
    End Sub

    Private Sub SearchBranches_QueryPopUp(sender As Object, e As System.ComponentModel.CancelEventArgs) Handles SearchBranches.QueryPopUp
        '  loadBrancehs()
    End Sub

    Private Sub LoadingSalaryPosted()
        'If Me.IsHandleCreated = False Then
        '    Exit Sub
        'End If
        Dim GetAddField As String

        Try

            Dim Sql As New SQLControl
            Sql.SqlTrueTimeRunQuery(" select FieldString from AddCustomField ")
            GetAddField = Sql.SQLDS.Tables(0).Rows(0).Item("FieldString")
            If String.IsNullOrEmpty(GetAddField) Or IsDBNull(Sql.SQLDS.Tables(0).Rows(0).Item("FieldString")) Then
                GetAddField = " "
            Else
                GetAddField += " As CustomField, "
            End If
        Catch ex As Exception
            GetAddField = ""
        End Try

        Try
            Dim sql As New SQLControl
            Dim SqlString As String
            Dim _Branch As String = SearchBranches.Text
            Dim _Department As String = SearchDepartment.Text
            Dim _Position As String = SearchPosition.Text
            Dim _Employees As String = SearchEmployees.EditValue
            Dim _DateFrom As String = Format(DateEditFrom.EditValue, "yyyy-MM-dd")
            Dim _DateTo As String = Format(DateEditTo.EditValue, "yyyy-MM-dd")

            SqlString = " SELECT  " & GetAddField & " A.[ID],A.[DateFrom],A.[DateTo] ,A.[DocMonth] ,A.[DocYear] ,A.[EmployeeID], IsNull(A.[IncomeTAX],0) As IncomeTAX  
                              ,C.[Code] as Currency  ,A.[SalaryMonth] ,A.[BonusAmount]
                             ,A.[Transport] ,A.[Additions] ,A.[LeavesAmount] ,A.[Payment] ,A.[GrossSalary] ,A.[MonthDays] ,A.[ActualDays]
                             ,A.[VocationDays] ,A.[WeekOffDays] ,A.[AbsenceDays] ,A.[HouresRequired] ,A.[ActualHoures] ,A.[VocationBegBalance] ,A.[AccruedVocationDays]
                             ,A.[VocationCurrentBalance] ,A.[VocationAtEndYear] ,A.[VocationSick] ,CAST(A.[NetSalary] AS int) As [NetSalary] ,IsNull(A.HouresNetBonus,'00:00') as HouresNetBonus,A.HouresNetLeaves,ArchiveStatus,AbsenceAmount,A.SalaryNote,IsNull(A.leavesIsAdjusted,0) as leavesIsAdjusted,IsNull(SavingsFund,0) as SavingsFund "
            If CheckDataFromEmpData.Checked = False Then
                SqlString &= " ,A.[EmployeeNoAsAcc],A.[EmployeeName],A.[Branch] ,A.[Department] ,A.[JobName] ,A.[BeginDate],A.[Indenty],A.[BankName],A.[BankNo],A.[BankBranch],A.IBAN,A.ProcessType,Case when E.[Active]=1 then N'فعال' else N'غير فعال' end as  Active,A.SalaryPerHour,A.SalaryPerDay "
            Else
                SqlString &= " ,E.SalaryAccountNo as EmployeeNoAsAcc ,E.[EmployeeName],E.[Branch] ,E.[Department] ,E.[JobName] ,E.DateOfStart as BeginDate,E.[Indenty],E.[BankName],E.[BankNo],E.[BankBranch],E.IBAN,E.ProcessType,E.Active,Case when E.[Active]=1 then N'فعال' else 'غير فعال' end as  Active,E.MonthlyHouresRequired,E.SalaryPerHour,E.SalaryPerDay  "
            End If
            SqlString &= " FROM [AttRawatebArchive] A  
                      Left join EmployeesData E on E.EmployeeID =A.EmployeeID
                      Left join [Dbo].[Currency] C on C.CurrID =A.Currency
                      Where A.[ID] > 0 "

            If CheckDataFromEmpData.Checked = False Then
                If Not String.IsNullOrEmpty(_Branch) Then SqlString &= " And A.Branch = N'" & _Branch & "'"
                If Not String.IsNullOrEmpty(_Department) Then SqlString &= " And A.Department = N'" & _Department & "'"
                If Not String.IsNullOrEmpty(_Position) Then SqlString &= " And A.JobName = N'" & _Position & "'"
            Else
                If Not String.IsNullOrEmpty(_Branch) Then SqlString &= " And E.Branch = N'" & _Branch & "'"
                If Not String.IsNullOrEmpty(_Department) Then SqlString &= " And E.Department = N'" & _Department & "'"
                If Not String.IsNullOrEmpty(_Position) Then SqlString &= " And E.JobName = N'" & _Position & "'"

            End If
            If Not String.IsNullOrEmpty(_Employees) Then SqlString &= " And A.EmployeeID = '" & _Employees & "'"
            If Not String.IsNullOrEmpty(_DateFrom) AndAlso Not String.IsNullOrEmpty(_DateTo) Then
                SqlString &= " and (DateFrom  between '" & _DateFrom & "'  and '" & _DateTo & "' )
                               and (DateTo between '" & _DateFrom & "' and '" & _DateTo & "') "
            End If

            If sql.SqlTrueTimeRunQuery(SqlString) = True Then
                GridControl1.DataSource = sql.SQLDS.Tables(0)
                PivotGridControl1.DataSource = sql.SQLDS.Tables(0)
                BandedGridView1.BestFitColumns()
            Else
                MsgBoxShowError(" خطا ")
            End If

        Catch ex As Exception
            GridControl1.DataSource = Nothing
            MsgBox(ex.ToString)
        End Try


        ColCustomField.Caption = GetFieldName()


        ' BandedGridView1.OptionsView.ColumnAutoWidth = False
        gridBand3.Visible = True
        BandedGridView1.BestFitColumns()

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        LoadingSalaryPosted()
    End Sub

    Private Sub SearchEmployees_EditValueChanged(sender As Object, e As EventArgs) Handles SearchEmployees.QueryPopUp
        LoadEmployees()
    End Sub
    Private Sub GetAccess_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        If CheckIfFormExist(Me.Name) = False Or HasAccessOnForm(Me.Name, "QueryAccess") = False Then
            Me.Close()
            MsgBox("لا يوجد صلاحية")
        End If
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        ColCustomField.Visible = True
        Dim _Field As String = "0"
        Dim _FieldName As String = "0"
        Try
            Dim Sql As New SQLControl
            Dim SqlString As String
            SqlString = " Select FieldString,FieldName from [AddCustomField] where [ReportName]= '" & Me.Name & "'"
            Sql.SqlTrueTimeRunQuery(SqlString)
            _Field = Sql.SQLDS.Tables(0).Rows(0).Item("FieldString")
            _FieldName = Sql.SQLDS.Tables(0).Rows(0).Item("FieldName")
        Catch ex As Exception
            _Field = "0"
        End Try


        If _Field = "0" Then
            AddCustomField.EquationString.Text = ""
            AddCustomField.FieldName.Text = ""
        Else
            AddCustomField.EquationString.Text = _Field
            AddCustomField.FieldName.Text = _FieldName
        End If
        AddCustomField.ShowDialog()
    End Sub

    Private Function GetFieldName() As String
        Dim _FieldName As String = "0"
        Try
            Dim Sql As New SQLControl
            Dim SqlString As String
            SqlString = " Select FieldName from [AddCustomField] where [ReportName]= '" & Me.Name & "'"
            Sql.SqlTrueTimeRunQuery(SqlString)
            _FieldName = Sql.SQLDS.Tables(0).Rows(0).Item("FieldName")
        Catch ex As Exception
            _FieldName = "0"
        End Try

        Return _FieldName
    End Function

    Private Sub CheckShowEmployeesData_CheckedChanged(sender As Object, e As EventArgs) Handles CheckShowEmployeesData.CheckedChanged
        'Select Case CheckShowEmployeesData.CheckState
        '    Case True
        '        colBranch.Visible = True
        '        colDepartment.Visible = True
        '        colJobName.Visible = True
        '        colBeginDate.Visible = True
        '        ColIndenty.Visible = True
        '        ColBankName.Visible = True
        '        ColBankNo.Visible = True
        '        ColBankBranch.Visible = True
        '    Case False
        '        colBranch.Visible = False
        '        colDepartment.Visible = False
        '        colJobName.Visible = False
        '        colBeginDate.Visible = False
        '        ColIndenty.Visible = False
        '        ColBankName.Visible = False
        '        ColBankNo.Visible = False
        '        ColBankBranch.Visible = False
        'End Select
        gridBandEmployeesDetails.Visible = CheckShowEmployeesData.CheckState
    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        PostSalary(False)
    End Sub
    Private Sub PostSalary(_Print As Boolean)
        Dim J As Integer = 0
        Dim selectedRowHandles As Integer() = BandedGridView1.GetSelectedRows()
        If selectedRowHandles.Length = 0 Then
            MsgBox("خطأ: لم يتم اختيار أي قسيمة راتب")
            Exit Sub
        End If
        'If XtraMessageBox.Show("هل تريد ترحيل  قسيمة عدد " & selectedRowHandles.Length, "تنبيه", MessageBoxButtons.YesNo) <> DialogResult.Yes Then
        '    Exit Sub
        'End If
        SplashScreenManager.ShowForm(Me, GetType(WaitForm11), True, True, False)
        For i As Integer = 0 To selectedRowHandles.Length - 1
            Dim _ID As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "ID")
            Dim _Status As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "ArchiveStatus")
            SplashScreenManager.Default.SetWaitFormDescription(i + 1 & " From " & selectedRowHandles.Length)
            If Not String.IsNullOrEmpty(CStr(_ID)) And _Status = 0 Then
                Dim Sql As New SQLControl
                Sql.SqlTrueTimeRunQuery(" Update [AttRawatebArchive] Set ArchiveStatus =1 where ID=" & _ID)
                BandedGridView1.SetRowCellValue(selectedRowHandles(i), "ArchiveStatus", 1)
                If _Print = True Then PrintSalaryDocument(_ID, "Print")
                J = J + 1
            End If
        Next
        SplashScreenManager.CloseForm(False)
        'MsgBoxShowSuccess("تم ترحيل قسيمة راتب عدد " & J)
        'LoadingSalaryPosted()
    End Sub
    Private Sub BarButtonItem8_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem8.ItemClick
        Dim selectedRowHandles As Integer() = BandedGridView1.GetSelectedRows()
        If selectedRowHandles.Length = 0 Then
            MsgBox("خطأ: لم يتم اختيار أي قسيمة راتب")
            Exit Sub
        End If
        If XtraMessageBox.Show("هل تريد ارسال  قسيمة عدد " & selectedRowHandles.Length, "تنبيه", MessageBoxButtons.YesNo) <> DialogResult.Yes Then
            Exit Sub
        End If
        SplashScreenManager.ShowForm(Me, GetType(WaitForm11), True, True, False)
        Dim _DocID, _EmpID As Integer
        Dim _EmpName As String
        With BandedGridView1
            For i As Integer = 0 To selectedRowHandles.Length - 1
                _DocID = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "ID")
                _EmpID = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "EmployeeID")
                _EmpName = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "EmployeeName")
                Dim _MobileNo As String = GetEmployeeData(_EmpID).Mobile
                If _MobileNo <> "0" And Not String.IsNullOrEmpty(_MobileNo) Then
                    SplashScreenManager.Default.SetWaitFormDescription(i + 1 & " From " & selectedRowHandles.Length)
                    PrintSalaryDocument(_DocID, "Pdf")
                    SendFileToWhatsApp(_MobileNo, "Salary.pdf", " قسيمة راتب ", "", _EmpName)
                End If
            Next i
        End With
        SplashScreenManager.CloseForm(False)
    End Sub

    Private Sub CheckEdit1_CheckedChanged(sender As Object, e As EventArgs) Handles CheckAutoFit.CheckedChanged
        If CheckAutoFit.Checked = True Then
            BandedGridView1.OptionsView.ColumnAutoWidth = True
        Else
            BandedGridView1.OptionsView.ColumnAutoWidth = False
        End If
        BandedGridView1.BestFitColumns()
    End Sub
    Private Sub CheckDataFromEmpData_CheckedChanged(sender As Object, e As EventArgs) Handles CheckDataFromEmpData.CheckedChanged
        Select Case CheckDataFromEmpData.Checked
            Case True
                Me.SearchBranches.Properties.DataSource = GetEmployeesBranches()
                Me.SearchDepartment.Properties.DataSource = GetEmployeesDepartments()
                Me.SearchPosition.Properties.DataSource = GetEmployeesPositions()
            Case False
                Me.SearchBranches.Properties.DataSource = GetEmployeesBranchesFromPosted()
                Me.SearchDepartment.Properties.DataSource = GetEmployeesDepartmentsFromPosted()
                Me.SearchPosition.Properties.DataSource = GetEmployeesPositionsFromPosted()
        End Select
    End Sub

    Private Function GetEmployeesBranchesFromPosted() As DataTable
        Dim _Table As New DataTable
        Try
            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(" SELECT DISTINCT Branch   FROM [dbo].[AttRawatebArchive] ")
            _Table = sql.SQLDS.Tables(0)
        Catch ex As Exception

        End Try
        Return _Table
    End Function
    Private Function GetEmployeesDepartmentsFromPosted() As DataTable
        Dim _Table As New DataTable
        Try
            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(" SELECT DISTINCT Department   FROM [dbo].[AttRawatebArchive]")
            _Table = sql.SQLDS.Tables(0)
        Catch ex As Exception

        End Try
        Return _Table
    End Function
    Private Function GetEmployeesPositionsFromPosted() As DataTable
        Dim _Table As New DataTable
        Try
            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(" SELECT DISTINCT [JobName] as Positions   FROM [dbo].[AttRawatebArchive] ")
            _Table = sql.SQLDS.Tables(0)
        Catch ex As Exception

        End Try
        Return _Table
    End Function
    Private Sub PrintDocumentes()
        Dim _DocID As Integer
        With BandedGridView1
            For i As Integer = 0 To .DataRowCount - 1
                If BandedGridView1.IsRowSelected(i) = True Then
                    _DocID = BandedGridView1.GetRowCellValue(i, "ID")
                    PrintSalaryDocument(_DocID, "Print")
                End If
            Next i
        End With
    End Sub
    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItemPrintSalaryDocument.ItemClick
        PrintDocumentes()
    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        colID.OptionsColumn.Printable = True
        ColDateFrom.OptionsColumn.Printable = True
        ColDateTo.OptionsColumn.Printable = True
        Me.gridBand3.Visible = True
        GridControl1.ShowPrintPreview()
        colID.OptionsColumn.Printable = False
        ColDateFrom.OptionsColumn.Printable = False
        ColDateTo.OptionsColumn.Printable = False
    End Sub

    Private Sub BarButtonItem4_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem4.ItemClick
        PostSalary(True)
    End Sub

    Private Sub BarButtonItem3_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem3.ItemClick
        LoadingSalaryPosted()
    End Sub

    Private Sub RepositoryDocID_OpenLink(sender As Object, e As Controls.OpenLinkEventArgs) Handles RepositoryDocID.OpenLink
        ' SplashScreenManager.ShowForm(Me, GetType(WaitForm11), True, True, False)
        Dim _DocID As Integer
        _DocID = BandedGridView1.GetFocusedRowCellValue("ID")
        PrintSalaryDocument(_DocID, "Preview")
        'SplashScreenManager.CloseForm(False)
    End Sub

    Private Sub BarButtonItem5_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem5.ItemClick

        If Me.BandedGridView1.OptionsSelection.MultiSelectMode = GridMultiSelectMode.CheckBoxRowSelect Then
            Me.BandedGridView1.OptionsSelection.MultiSelectMode = GridMultiSelectMode.RowSelect
        Else
            Me.BandedGridView1.OptionsSelection.MultiSelectMode = GridMultiSelectMode.CheckBoxRowSelect
        End If
    End Sub

    Private Sub RepositoryEmployeeID_OpenLink(sender As Object, e As Controls.OpenLinkEventArgs) Handles RepositoryEmployeeID.OpenLink
        Dim f As New EmployeesEdit
        With f
            .EmployeeIDTextEdit.Text = BandedGridView1.GetFocusedRowCellValue("EmployeeID")
            .EmployeeNameTextEdit.Select()
            If .ShowDialog() <> DialogResult.OK Then
                'GetSubscritions("TileBarActive")
            End If
        End With
    End Sub
    Protected Sub TabbedGroup_CustomHeaderButtonClickn_Click(ByVal sender As System.Object,
                       ByVal e As DevExpress.XtraTab.ViewInfo.CustomHeaderButtonEventArgs) Handles TabbedControlGroup1.CustomHeaderButtonClick
        If e.Button.Tag = "Print" AndAlso TabbedControlGroup1.SelectedTabPageName = "LayoutControlGroupSalary" Then
            GridControl1.ShowPrintPreview()
        End If
        If e.Button.Tag = "Print" AndAlso TabbedControlGroup1.SelectedTabPageName = "LayoutControlGroupPivot" Then
            PivotGridControl1.ShowPrintPreview()
        End If

    End Sub

    Private Sub BarButtonItem6_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem6.ItemClick
        If _ShowChart = False Then
            LayoutControlItemChart.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always
            BarButtonItem7.Visibility = DevExpress.XtraBars.BarItemVisibility.Always
            ChartControl1.SeriesTemplate.LabelsVisibility = True
            ChartControl1.CrosshairEnabled = True
            _ShowChart = True
        Else
            LayoutControlItemChart.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never
            BarButtonItem7.Visibility = DevExpress.XtraBars.BarItemVisibility.Never
            ChartControl1.SeriesTemplate.LabelsVisibility = True
            ChartControl1.CrosshairEnabled = True
            _ShowChart = False
        End If
    End Sub

    Private Sub BarButtonItem7_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem7.ItemClick
        ChartControl1.ShowPrintPreview()
    End Sub

    Private Sub BarButtonItem9_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItemDelete.ItemClick


        Dim selectedRowHandles As Integer() = BandedGridView1.GetSelectedRows()
        If selectedRowHandles.Length = 0 Then
            MsgBox("خطأ: لم يتم اختيار أي قسيمة راتب")
            Exit Sub
        End If
        If XtraMessageBox.Show("هل تريد حذف قسيمة عدد " & selectedRowHandles.Length, "تنبيه", MessageBoxButtons.YesNo) <> DialogResult.Yes Then
            Exit Sub
        End If

        Dim _DocID As Integer
        Dim _DocStatus As Integer
        With BandedGridView1
            For i As Integer = 0 To .DataRowCount - 1
                If BandedGridView1.IsRowSelected(i) = True Then
                    _DocID = BandedGridView1.GetRowCellValue(i, "ID")
                    _DocStatus = BandedGridView1.GetRowCellValue(i, "ArchiveStatus")
                    If _DocStatus = 0 Then
                        DeleteRelatedTransForSalaryDocument(_DocID)
                    Else
                        MsgBoxShowError(" قسيمة الراتب رقم " & _DocID & " مرحلة ولا يمكن حذفها ")
                    End If
                End If
            Next i
        End With
        LoadingSalaryPosted()
    End Sub

    Private Sub BandedGridView1_DoubleClick(sender As Object, e As EventArgs) Handles BandedGridView1.DoubleClick
        Dim ea As DXMouseEventArgs = TryCast(e, DXMouseEventArgs)
        Dim view As GridView = TryCast(sender, GridView)
        Dim info As GridHitInfo = view.CalcHitInfo(ea.Location)
        If info.InRow OrElse info.InRowCell Then
            Dim colFieldName As String = If(info.Column Is Nothing, "N/A", info.Column.FieldName)
            Select Case colFieldName
                Case "HouresNetLeaves", "LeavesAmount"
                    ShowAttLeavesProccessMonthly()
                Case "SalaryNote"
                    Dim _DocID As Integer = BandedGridView1.GetFocusedRowCellValue("ID")
                    Dim F As New SalaryPostedAddNote()
                    With F
                        ._DocID = _DocID
                        If .ShowDialog <> DialogResult.OK Then
                            BandedGridView1.SetFocusedRowCellValue("SalaryNote", ._Note)
                        End If
                    End With
            End Select

        End If
    End Sub

    Private Sub BarBtnAddNote_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarBtnAddNote.ItemClick
        Dim _DocID As Integer = BandedGridView1.GetFocusedRowCellValue("ID")
        Dim F As New SalaryPostedAddNote()
        With F
            ._DocID = _DocID
            If .ShowDialog <> DialogResult.OK Then
                BandedGridView1.SetFocusedRowCellValue("SalaryNote", ._Note)
            End If
        End With
    End Sub

    Private Sub BarButtonShowNotePreview_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonShowNotePreview.ItemClick
        Select Case BandedGridView1.OptionsView.ShowPreview
            Case True
                BandedGridView1.OptionsView.ShowPreview = False
            Case False
                BandedGridView1.OptionsView.ShowPreview = True
        End Select
    End Sub

    'Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
    '    gridBand3.Visible = False
    '    ShowGridPrintPreview()
    '    gridBand3.Visible = True
    'End Sub
    'Private Sub BandedGridView1_PrintInitialize(sender As System.Object, e As DevExpress.XtraGrid.Views.Base.PrintInitializeEventArgs)
    '    colID.OptionsColumn.Printable = True
    '    ColDateFrom.OptionsColumn.Printable = True
    '    ColDateTo.OptionsColumn.Printable = True
    '    Dim _DateFrom As String = DateEditFrom.DateTime
    '    Dim _Date__To As String = DateEditTo.DateTime
    '    Dim pb As PrintingSystemBase = CType(e.PrintingSystem, PrintingSystemBase)
    '    pb.PageSettings.Landscape = True
    '    pb.PageSettings.LeftMargin = 50
    '    pb.PageSettings.RightMargin = 50
    '    pb.PageSettings.TopMargin = 100
    '    TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Clear()
    '    TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Footer.Content.Clear()
    '    Dim sql As New SQLControl
    '    Dim SQLString As String = "Select CompanyName  from CompanyData"
    '    sql.SqlTrueTimeRunQuery(SQLString)
    '    If sql.SQLDS.Tables(0).Rows.Count = 0 Then Exit Sub
    '    Dim ComName As String = sql.SQLDS.Tables(0).Rows(0).Item("CompanyName")
    '    Dim _signatures = GetDocumentSignatures("AttSalariesReport")
    '    Dim Tawqe1 As String = "" & vbCrLf & " ............................:" & _signatures.signature1 & vbCrLf & vbCrLf & vbCrLf & " ............................:" & _signatures.signature3
    '    Dim Tawqe2 As String = "" & vbCrLf & " ............................:" & _signatures.signature2 & vbCrLf & vbCrLf & vbCrLf & " ............................:" & _signatures.signature4
    '    TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Footer.Content.AddRange(New String() {Tawqe1, "Pages: [Page # of Pages #]", Tawqe2})
    '    TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.AddRange(New String() {"تقرير الرواتب للفترة من " & _DateFrom & " الى " & _Date__To, ComName, " "})
    '    colID.OptionsColumn.Printable = False
    '    ColDateFrom.OptionsColumn.Printable = False
    '    ColDateTo.OptionsColumn.Printable = False
    'End Sub
    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        gridBand3.Visible = False
        BandedGridView1.BestFitColumns()
        BandedGridColumnNote.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Far
        Dim _Report As New AttSalariesReport
        With _Report
            .PrintableComponentContainer1.PrintableComponent = Me.GridControl1
            .XrLabelPeriodName.Text = " للفترة من " & DateEditFrom.Text & " الى " & DateEditTo.Text
            .ShowPreview
        End With
        BandedGridColumnNote.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Near
    End Sub
    Private Sub GridView1_CustomDrawFooterCell(sender As Object, e As FooterCellCustomDrawEventArgs) Handles BandedGridView1.CustomDrawFooterCell
        If e.Column.FieldName = "NetSalary" Then
            e.Appearance.TextOptions.HAlignment = HorzAlignment.Center
            e.Appearance.ForeColor = Color.FromArgb(255, 80, 0)
            'e.Appearance.BackColor = Color.FromArgb(1, 55, 99)
        End If
    End Sub
    'Private Sub ShowGridPrintPreview()
    '    Dim report As XtraReport = CreateReportFromGrid()
    '    report.Landscape = True
    '    report.Margins.Left = 50
    '    report.Margins.Right = 50
    '    report.Margins.Top = 20
    '    report.RightToLeft = True
    '    report.RightToLeftLayout = True
    '    Dim reportInfoBand As New ReportHeaderBand()
    '    report.Bands.Add(reportInfoBand)
    '    FillReportHeaderWithContent(reportInfoBand)
    '    Dim printTool As New ReportPrintTool(report)
    '    printTool.ShowRibbonPreview()
    'End Sub

    'Private Function CreateReportFromGrid() As XtraReport
    '    Return CreateReportFromGridUsingPCL(GridControl1)
    'End Function

    'Private Function CreateReportFromGridUsingPCL(ByVal grid As GridControl) As XtraReport
    '    Dim report = New XtraReport()
    '    Dim detailBand As DetailBand = New DetailBand()
    '    report.Bands.Add(detailBand)
    '    Dim pcl As PrintableComponentContainer = New PrintableComponentContainer()
    '    pcl.PrintableComponent = grid
    '    detailBand.Controls.Add(pcl)
    '    Return report
    'End Function

    'Private Sub FillReportHeaderWithContent(ByVal headerBand As Band)
    '    Dim _DateFrom As String = DateEditFrom.DateTime
    '    Dim _Date__To As String = DateEditTo.DateTime
    '    Dim pictureBox As XRPictureBox = New XRPictureBox()
    '    Dim image As Image = _Image
    '    pictureBox.ImageSource = New DevExpress.XtraPrinting.Drawing.ImageSource(image)
    '    pictureBox.Sizing = ImageSizeMode.ZoomImage
    '    pictureBox.SizeF = New SizeF(150, 50)
    '    pictureBox.LocationF = New PointF(0, 0)
    '    headerBand.Controls.Add(pictureBox)
    '    Dim pageInfo As XRPageInfo = New XRPageInfo()
    '    pageInfo.Font = New Font("Arial", 10.0F, FontStyle.Bold)
    '    pageInfo.PageInfo = pageInfo.StartPageNumber
    '    pageInfo.TextFormatString = "Pages: {0} de {1}"
    '    Dim ownerReport As XtraReport = (TryCast(headerBand.Report, XtraReport))
    '    pageInfo.SizeF = BestSizeEstimator.GetBoundsToFitText(pageInfo.TextFormatString, BrickStyle.CreateDefault(), 200, 96.0F).Size
    '    pageInfo.LocationF = New PointF(ownerReport.PageWidth - ownerReport.Margins.Left - ownerReport.Margins.Right - pageInfo.SizeF.Width, 20)
    '    headerBand.Controls.Add(pageInfo)
    '    Dim additionalMessage As XRLabel = New XRLabel()
    '    Dim additionalInfo As String
    '    If _Mode = "Attendance" Then
    '        additionalInfo = " كشف الدوام " & vbCrLf & " من  " & _DateFrom & " الى " & _Date__To
    '    Else
    '        additionalInfo = " كشف الرواتب " & vbCrLf & " من " & _DateFrom & " الى " & _Date__To
    '    End If
    '    additionalMessage.Text = additionalInfo
    '    additionalMessage.TextAlignment = TextAlignment.MiddleCenter
    '    additionalMessage.Font = New Font("Arial", 12.0F, FontStyle.Bold)
    '    'additionalMessage.ForeColor = Color.LightGreen
    '    additionalMessage.WordWrap = True
    '    additionalMessage.Multiline = True
    '    Dim optimalBounds As RectangleF = BestSizeEstimator.GetBoundsToFitText(additionalInfo, New BrickStyle(BorderSide.None, 0, Color.Empty, Color.Empty, additionalMessage.ForeColor, additionalMessage.Font, New BrickStringFormat()), 500.0F, 96.0F)
    '    additionalMessage.SizeF = optimalBounds.Size
    '    additionalMessage.LocationF = New PointF((ownerReport.PageWidth - ownerReport.Margins.Left - ownerReport.Margins.Right) / 2 - optimalBounds.Size.Width / 2, 10)
    '    headerBand.Controls.Add(additionalMessage)

    'End Sub
    'Private Sub CreateLogo()
    '    Try
    '        Dim cn As SqlConnection
    '        cn = New SqlConnection With {
    '            .ConnectionString = My.Settings.TrueTimeConnectionString
    '        }
    '        Dim cmd As New System.Data.SqlClient.SqlCommand("select CompanyLogo from [dbo].[CompanyData]  ")
    '        cn.Open()
    '        cmd.Connection = cn
    '        cmd.CommandType = CommandType.Text
    '        Dim ImgStream As New IO.MemoryStream(CType(cmd.ExecuteScalar, Byte()))
    '        _Image = Image.FromStream(ImgStream)
    '        ImgStream.Dispose()
    '        cmd.Connection.Close()
    '        cn.Close()
    '    Catch ex As Exception

    '    End Try
    'End Sub
    Private Sub ShowAttLeavesProccessMonthly()
        Dim _timeFunction As New TimeFunctions()
        Dim F As New AttLeavesProccessMonthly(BandedGridView1.GetFocusedRowCellValue("ID"))
        With F
            If Not IsDBNull(BandedGridView1.GetFocusedRowCellValue("HouresNetLeaves")) Then
                .LabelPeriod.Text = "خصم المغادرات للفترة من " & BandedGridView1.GetFocusedRowCellValue("DateFrom") & " الى " & BandedGridView1.GetFocusedRowCellValue("DateTo")
                .VocationDate.DateTime = BandedGridView1.GetFocusedRowCellValue("DateTo")
                .TextEmployeeID.Text = BandedGridView1.GetFocusedRowCellValue("EmployeeID")
                .SpanLeavesPeriod.TimeSpan = _timeFunction.ConvertText_hhmm_ToTimeSpan(BandedGridView1.GetFocusedRowCellValue("HouresNetLeaves"))
                .TextLastLeavesAmount.EditValue = CDec(BandedGridView1.GetFocusedRowCellValue("LeavesAmount"))
                ' .TextEmployeeName.Text = BandedGridView1.GetFocusedRowCellValue("EmployeeName")
                .LookUpEditVocations.EditValue = 1
                '.SpanMonthlyAllowedLeavesPeriod.TimeSpan = TimeSpan.ParseExact("08:00", "hh\:mm", Nothing)
                '.TextDayNo.EditValue = (.SpanLeavesPeriod.TimeSpan.TotalHours / .SpanMonthlyAllowedLeavesPeriod.TimeSpan.TotalHours).ToString("0.0")
                If .ShowDialog() <> DialogResult.OK Then
                    LoadingSalaryPosted()
                End If
            End If
        End With
    End Sub

    Private Sub BarButtonItem10_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonCopyAsTXT.ItemClick
        Try
            BandedGridView1.OptionsSelection.MultiSelect = True
            BandedGridView1.SelectAll()
            BandedGridView1.CopyToClipboard()
            MsgBoxShowSuccess(" تم نسخ التقرير بنجاح ")
        Catch ex As Exception
            XtraMessageBox.Show("خطا في عملية النسخ ، يرجى اعادة المحاولة")
        End Try
    End Sub

    Private Sub BarButtonItem2_ItemClick_1(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick
        Dim F As New SignaturesDocument
        With F
            .SrchDocName.EditValue = "AttSalariesReport"
            .SrchDocName.ReadOnly = True
            .ShowDialog()
        End With
    End Sub

    Private Sub BarButtonItem10_ItemClick_1(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem10.ItemClick
        Dim selectedRowHandles As Integer() = BandedGridView1.GetSelectedRows()
        If selectedRowHandles.Length = 0 Then
            MsgBox("خطأ: لم يتم اختيار أي قسيمة راتب")
            Exit Sub
        End If
        If XtraMessageBox.Show(" سيتم تقريب صافي الراتب لاقرب 5، هل تريد الاستمرار؟ " & selectedRowHandles.Length, "تنبيه", MessageBoxButtons.YesNo) <> DialogResult.Yes Then
            Exit Sub
        End If

        Dim _DocID As Integer
        Dim _NetSalary As Integer
        Dim J As Integer = 0
        With BandedGridView1
            For i As Integer = 0 To .DataRowCount - 1
                If BandedGridView1.IsRowSelected(i) = True Then
                    _DocID = BandedGridView1.GetRowCellValue(i, "ID")
                    _NetSalary = BandedGridView1.GetRowCellValue(i, "NetSalary")
                    If _NetSalary > 0 Then
                        UpdateNetSalary(_DocID, _NetSalary)
                        J += 1
                    End If
                End If
            Next i
        End With
        If J <> 0 Then
            MsgBoxShowSuccess(" تم تعديل قسائم الرواتب عدد " & J)
            LoadingSalaryPosted()
        End If
    End Sub
    Public Function CeilingFor5(ByVal value As Double) As Double
        If value > 0 Then
            ' Round up to the nearest multiple of 5
            Return Math.Ceiling(value / 5) * 5
        Else
            Return value
        End If
    End Function
    Private Sub UpdateNetSalary(_DocID As Integer, _Amount As Decimal)
        Dim sql As New SQLControl
        Dim sqlString As String
        sqlString = "   UPDATE [AttRawatebArchive]
                        SET NetSalary = " & CeilingFor5(_Amount) & "   where ID=" & _DocID
        sql.SqlTrueAccountingRunQuery(sqlString)
    End Sub
    Private Sub AdvancePaymentInserting(PaymentDate As String, EmployeeID As Integer, PaymentAmount As Decimal, PaymentNote As String, PaymentType As Integer)

        Try
            Dim sql As New SQLControl
            Dim InsertString As String = " INSERT INTO [AttEmployeePayments]
           ([PaymentDate]
           ,[EmployeeID]
           ,[PaymentAmount]
           ,[PaymentNote]
           ,[PaymentType],[PaymentBranch],[Status])
     VALUES
           ('" & PaymentDate & "'
           ,'" & EmployeeID & "'
           ," & PaymentAmount & "
           ,N'" & PaymentNote & "'
           ,N'" & PaymentType & "'
           ,N'" & "" & "',1)"

            If sql.SqlTrueTimeRunQuery(InsertString) = True Then

            End If
        Catch ex As Exception
            MsgBox("Try Again")
        End Try


    End Sub
    Private Function UpdatePayment(_DocID As Integer, _PaymentAmount As Decimal) As Boolean
        Dim Sql As New SQLControl
        Dim SqlString As String
        SqlString = " Update [AttRawatebArchive] set 
                                      [NetSalary]=[NetSalary]-" & _PaymentAmount & ",Payment=Payment+" & _PaymentAmount & " Where ID=" & _DocID & "; "
        Return Sql.SqlTrueAccountingRunQuery(SqlString) = True
    End Function
    Private Sub BarButtonItem11_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem11.ItemClick
        Dim selectedRowHandles As Integer() = BandedGridView1.GetSelectedRows()
        If selectedRowHandles.Length = 0 Then
            MsgBox("خطأ: لم يتم اختيار أي قسيمة راتب")
            Exit Sub
        End If
        If XtraMessageBox.Show(" سيتم اصدار خصميات بصافي الراتب ل، هل تريد الاستمرار؟ " & selectedRowHandles.Length, "تنبيه", MessageBoxButtons.YesNo) <> DialogResult.Yes Then
            Exit Sub
        End If

        Dim _DocID As Integer
        Dim _PaymentDate As String
        Dim _EmployeeID As Integer
        Dim _PaymentAmount As Decimal
        Dim _PaymentNote As String = " اغلاق الراتب "
        Dim J As Integer = 0
        With BandedGridView1
            For i As Integer = 0 To .DataRowCount - 1
                If BandedGridView1.IsRowSelected(i) = True Then
                    _PaymentAmount = BandedGridView1.GetRowCellValue(i, "NetSalary")
                    If _PaymentAmount > 0 Then
                        _PaymentDate = Format(CDate(BandedGridView1.GetRowCellValue(i, "DateTo")), "yyyy-MM-dd")
                        _EmployeeID = CInt(BandedGridView1.GetRowCellValue(i, "EmployeeID"))
                        _DocID = CInt(BandedGridView1.GetRowCellValue(i, "ID"))
                        AdvancePaymentInserting(_PaymentDate, _EmployeeID, _PaymentAmount, _PaymentNote, 7)
                        UpdatePayment(_DocID, _PaymentAmount)
                        J += 1
                    End If
                End If
            Next i
        End With
        If J <> 0 Then
            MsgBoxShowSuccess(" تم تعديل قسائم الرواتب عدد " & J)
            LoadingSalaryPosted()
        End If
    End Sub

    Private Sub PrintAttSheets()
        Dim selectedRowHandles As Integer() = BandedGridView1.GetSelectedRows()
        If selectedRowHandles.Length = 0 Then
            MsgBoxShowError(" لم يتم اختيار الموظفين ")
            Exit Sub
        End If

        Dim j As Integer = 0

        For i As Integer = 0 To selectedRowHandles.Length - 1
            Dim _EmployeeID As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "EmployeeID")
            Dim _EmployeeName As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "EmployeeName")
            Dim _ProcessType As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "ProcessType")
            Dim _DateFrom As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "DateFrom")
            Dim _DateTo As Object = BandedGridView1.GetRowCellValue(selectedRowHandles(i), "DateTo")
            Dim _MobileNo As String = GetEmployeeData(CInt(_EmployeeID)).Mobile
            Dim _DocID As Integer = 0
            Dim _DocStatus As Integer = 0
            Dim _DocData = GetSalaryDocumentIDAndStatusIfExist(_EmployeeID, Format(CDate(_DateFrom), "yyyy-MM-dd"), Format(CDate(_DateTo), "yyyy-MM-dd"))
            _DocID = _DocData.DocID
            _DocStatus = _DocData.DocStatus
            'If _DocID > 0 Then
            '    If _DocStatus <> 0 Then
            '        MsgBoxShowError(" يوجد قسيمة مرحلة للموظف " & _EmployeeName)
            '        Continue For
            '    Else
            '        DeleteRelatedTransForSalaryDocument(_DocID)
            '    End If
            'End If


            Select Case CInt(_ProcessType)
                Case 2
                    Dim f As New AttRawatebByHouresRequired
                    With f
                        GetFormType("Dawam")
                        .DateEdit1.DateTime = CDate(_DateFrom)
                        .DateEdit2.DateTime = CDate(_DateTo)
                        .SearchLookUpEdit1.EditValue = _EmployeeID
                        ._OpenForPrint = True
                        ._PrintSalayDocument = False
                        ._SaveSalary = False
                        ._EmployeesCount = selectedRowHandles.Length
                        ._TheOptionPrint = "Pdf"
                        .Show()
                        SendFileToWhatsApp(_MobileNo, "تقرير الدوام.Pdf", "تقرير الدوام", String.Empty, _EmployeeName)
                    End With
                Case 3, 6
                    Dim f As New AttRawatebByHouresRequired
                    With f
                        GetFormType("Dawam2")
                        .DateEdit1.DateTime = CDate(_DateFrom)
                        .DateEdit2.DateTime = CDate(_DateTo)
                        .SearchLookUpEdit1.EditValue = _EmployeeID
                        ._OpenForPrint = True
                        ._PrintSalayDocument = False
                        ._SaveSalary = False
                        ._EmployeesCount = selectedRowHandles.Length
                        ._TheOptionPrint = "Pdf"
                        ' ._PrintAtt = CheckPrintAtt.CheckState
                        .Show()
                        SendFileToWhatsApp(_MobileNo, "تقرير الدوام.Pdf", "تقرير الدوام", String.Empty, _EmployeeName)
                    End With
                Case 7
                    Dim f As New AttRawatebByHouresRequired
                    With f
                        GetFormType("DailyAtt")
                        .DateEdit1.DateTime = CDate(_DateFrom)
                        .DateEdit2.DateTime = CDate(_DateTo)
                        .SearchLookUpEdit1.EditValue = _EmployeeID
                        ._OpenForPrint = True
                        ._PrintSalayDocument = False
                        ._SaveSalary = False
                        ._EmployeesCount = selectedRowHandles.Length
                        ._TheOptionPrint = "Pdf"
                        ' ._PrintAtt = CheckPrintAtt.CheckState
                        .Show()
                        SendFileToWhatsApp(_MobileNo, "تقرير الدوام.Pdf", "تقرير الدوام", String.Empty, _EmployeeName)
                    End With
                Case 1, 4, 5
                    Dim f As New AttRawatebByShift
                    With f
                        GetFormType("Dawam")
                        ._EmployeeIDFromSalariesPublish = 0
                        .DateEdit1.DateTime = CDate(_DateFrom)
                        .DateEdit2.DateTime = CDate(_DateTo)
                        .SearchLookUpEdit1.EditValue = _EmployeeID
                        ._EmployeeIDFromSalariesPublish = _EmployeeID
                        ._OpenForPrint = True
                        ._PrintSalayDocument = True
                        ._PrintSalary = True
                        ._TheOptionPrint = "Pdf"
                        .Show()
                        SendFileToWhatsApp(_MobileNo, "تقرير الدوام.Pdf", "تقرير الدوام", String.Empty, _EmployeeName)
                    End With
            End Select
            j += 1

        Next
        MsgBoxShowSuccess(" تم اصدار الكشوفات " & j)


    End Sub

    Private Sub BarSendAttSheetsForEmployees_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarSendAttSheetsForEmployees.ItemClick
        PrintAttSheets()
    End Sub
End Class