Imports DevExpress.XtraEditors
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraPrinting
Imports DocumentFormat.OpenXml.Drawing.Spreadsheet

Public Class VocationsQuery
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub GridView1_PrintInitialize(sender As System.Object, e As DevExpress.XtraGrid.Views.Base.PrintInitializeEventArgs) Handles GridView1.PrintInitialize

        Dim pb As PrintingSystemBase = CType(e.PrintingSystem, PrintingSystemBase)
        pb.PageSettings.Landscape = False
        pb.PageSettings.LeftMargin = 0
        pb.PageSettings.RightMargin = 0
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Clear()
        Dim sql As New SQLControl
        Dim SQLString As String = "Select CompanyName  from CompanyData"
        sql.SqlTrueTimeRunQuery(SQLString)
        If sql.SQLDS.Tables(0).Rows.Count = 0 Then Exit Sub
        Dim ComName As String = sql.SQLDS.Tables(0).Rows(0).Item("CompanyName")
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Footer.Content.AddRange(New String() _
{"  ", Now(), "Pages: [Page # of Pages #]"})
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Add _
(" " & "كشف الاجازات   " & " / " & SearchVocationType.Text)
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Add(ComName)
        Dim _FromToDate As String = " من تاريخ:   " & DateFrom.EditValue & " الى تاريخ: " & " " & DateTo.EditValue
        TryCast(e.Link.PageHeaderFooter, PageHeaderFooter).Header.Content.Add(_FromToDate)
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub GridView1_CustomDrawRowIndicator(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs) Handles GridView1.CustomDrawRowIndicator
        Dim gw As GridView = TryCast(sender, GridView)
        If e.RowHandle >= 0 Then
            e.Info.DisplayText = (e.RowHandle + 1).ToString
        End If
    End Sub

    Private Sub VocationsQuery_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.VocationsTypesTableAdapter.Fill(Me.TrueTimeDataSet.VocationsTypes)
        Me.EmployeesPositionsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesPositions)
        Me.EmployeesBranchesTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesBranches)
        Me.EmployeesDepartmentsTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesDepartments)
        Me.EmployeesData1TableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData1)
        Me.DateTo.DateTime = Today

        Dim startDt As New Date(Today.Year, 1, 1)
        Me.DateFrom.DateTime = startDt
        Me.KeyPreview = True
        UpdateData()
    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        UpdateData()
    End Sub

    Private Sub AddVocation_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.F5 Then
            UpdateData()
        ElseIf e.KeyCode = Keys.F12 Then
            ShowPrint()
        End If

    End Sub


    Private Sub UpdateData()


        Try
            GridControl1.DataSource = String.Empty
            Me.RepositoryItemVocationSource.DataSource = CreateVocationsSource()
            Dim SqlString As String
            Dim sql As New SQLControl
            Dim VocationType As String = SearchVocationType.EditValue
            If String.IsNullOrEmpty(VocationType) Then VocationType = "Null"

            Dim Department As String = LookUpEditDepartment.EditValue
            If String.IsNullOrEmpty(Department) Then Department = "Null"

            Dim Branch As String = LookUpEditBranch.EditValue
            If String.IsNullOrEmpty(Branch) Then Branch = "Null"

            Dim DateFrom As String = Format(Me.DateFrom.DateTime, "yyyy-MM-dd")
            Dim DateTo As String = Format(Me.DateTo.DateTime, "yyyy-MM-dd")

            SqlString = " Select VocID,VocDate,Vocations.EmployeeID,VocationType,VocationBeginingBalance,month(FromDate) As VocMonth,
                             FromDate,ToDate,NoDays,NoteDetails,EmployeesData.EmployeeName,EmployeesData.Department,EmployeesData.JobName,EmployeesData.Branch,EmployeesData.[Active],[VocationSource],SalaryDocumentID
                      From Vocations,EmployeesData
                      Where  Vocations.EmployeeID = EmployeesData.EmployeeID"
            SqlString = SqlString + " And FromDate Between '" & DateFrom & "' And '" & DateTo & "'"
            If SearchEmployee.EditValue <> 0 Then SqlString = SqlString + " And Vocations.EmployeeID = " & SearchEmployee.EditValue
            If VocationType <> "Null" Then SqlString = SqlString + " And Vocations.VocationType = '" & VocationType & "'"
            If Department <> "Null" Then SqlString = SqlString + " And EmployeesData.Department = N'" & Department & "'"
            If Branch <> "Null" Then SqlString = SqlString + " And EmployeesData.Branch = N'" & Branch & "'"
            If CheckEditCheckActive.Checked = True Then SqlString = SqlString + " And EmployeesData.Active=1"
            SqlString = SqlString + " Order By VocID Desc "
            sql.SqlTrueTimeRunQuery(SqlString)
            If sql.SQLDS.Tables(0).Rows.Count = 0 Then Exit Sub
            GridControl1.DataSource = sql.SQLDS.Tables(0)

            GridView1.BestFitColumns()
            '  Grouping()

        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try


    End Sub

    Private Sub Grouping()
        Select Case RadioGroup1.EditValue
            Case 0
                GridView1.ClearGrouping()
            Case 1
                colEmployeeName.GroupIndex = 0
            Case 2
                colDepartment.GroupIndex = 0
            Case 3
                colBranch.GroupIndex = 0
            Case 4
                colJobName.GroupIndex = 0
            Case 5
                ColMonth.GroupIndex = 0
        End Select
    End Sub

    Private Sub RadioGroup1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles RadioGroup1.SelectedIndexChanged
        Grouping()
    End Sub

    Private Sub RadioGroup2_SelectedIndexChanged(sender As Object, e As EventArgs) Handles RadioGroup2.SelectedIndexChanged
        Select Case RadioGroup2.EditValue
            Case 1
                GridView1.ExpandAllGroups()

            Case 2
                GridView1.CollapseAllGroups()
        End Select
    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        ShowPrint()
    End Sub

    Private Sub ShowPrint()
        If GridControl1.IsPrintingAvailable = False Then Exit Sub
        If GlobalVariables._SystemLanguage = "Arabic" Then
            If GridView1.RowCount = 0 Then MsgBox("التقرير فارغ") : Exit Sub
        Else
            If GridView1.RowCount = 0 Then MsgBox("Empty Report") : Exit Sub
        End If

        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub

    Private Sub GridControl1_DoubleClick(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        OpenVocation()
    End Sub
    Private Sub GetAccess_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        If CheckIfFormExist(Me.Name) = False Or HasAccessOnForm(Me.Name, "QueryAccess") = False Then
            Me.Close()
            MsgBox("لا يوجد صلاحية")
        End If
    End Sub

    Private Sub RepositoryDocNo_OpenLink(sender As Object, e As DevExpress.XtraEditors.Controls.OpenLinkEventArgs) Handles RepositoryDocNo.OpenLink
        OpenVocation()
    End Sub
    Private Sub OpenVocation()
        Dim f As New AddVocation
        With f
            .TextID.Text = GridView1.GetFocusedRowCellValue("VocID").ToString
            .TextNewOrOld.Text = "Old"
            If .ShowDialog <> DialogResult.OK Then
                UpdateData()
            End If
        End With
        'If GridView1.GetFocusedRowCellValue("VocID").ToString <> String.Empty Then
        '    My.Forms.AddVocation.TextID.Text = GridView1.GetFocusedRowCellValue("VocID").ToString
        '    My.Forms.AddVocation.TextNewOrOld.Text = "Old"
        '    'My.Forms.AddVocation.FromFrom.Text = "True"
        '    '  My.Forms.AddVocation.opend = False
        '    If AddVocation.ShowDialog() = DialogResult.OK Then
        '        MsgBox("ok")
        '    Else
        '        UpdateData()
        '    End If

        'End If
    End Sub

    Private Sub SimpleButton1_Click_1(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Dim f As New AddVocation
        With f
            .TextNewOrOld.Text = "New"
            If .ShowDialog <> DialogResult.OK Then
                UpdateData()
            End If
        End With
        '  AddVocation.Show()
    End Sub

End Class