Public Class AttChartDiagram
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        'EmployeesDataTableAdapter1.Fill(TrueTimeDataSet1.EmployeesData)
    End Sub
End Class