Imports DevExpress.XtraEditors
Imports DevExpress.XtraExport.Helpers
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid

Public Class AttTransReport
    Dim _AlqudsCig As Boolean
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource

        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        '  AddHandler GridView1.CustomDrawCell, AddressOf GridView1_CustomDrawCell
    End Sub

    Private Sub GetAttTrans_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.EmployeesDataTableAdapter.Fill(Me.TrueTimeDataSet.EmployeesData)
        Me.CheckTypesTableAdapter.Fill(Me.TrueTimeDataSet.CheckTypes)
        Me.DateEdit2.DateTime = Today
        Me.DateEdit1.DateTime = Today.AddDays(-1)
        Me.DateEdit3.DateTime = Now.AddDays(-1)
        Gettsettings()
        If CheckIfHasAccessToAddAttendanceTrans() = False Then
            BtnAddAttTrans.Visible = False
            PanelControlAddAtt.Visible = False
        End If
        If CheckIfHasAccessToEditAttendanceTrans() = False Then
            ColAttEdit.Visible = False
        End If
        If CheckIfHasAccessToDeleteAttendanceTrans() = False Then
            ColAttDelete.Visible = False
        End If
    End Sub
    Private Sub Gettsettings()

    End Sub

    Private Sub TileItem1_ItemClick(sTender As Object, e As DevExpress.XtraEditors.TileItemEventArgs)

    End Sub
    Private Sub LoadAttData()
        Dim focusedRow As Integer = GridView2.FocusedRowHandle
        Dim Sql As New SQLControl
        Dim DateFrom As String = Format(DateEdit1.DateTime, "yyyy-MM-dd") & " 00:00:00"
        Dim DateTo As String = Format(DateEdit2.DateTime, "yyyy-MM-dd") & " 23:59:59"
        Dim SQLString2 As String = " Select AttCHECKINOUT.[ID] as TransID ,USERID,EmployeeName, CHECKTIME,CHECKTYPE , Edited , EditedDate,Machines.[MachineAlias],EditedType
                                    FROM AttCHECKINOUT
                                    left join EmployeesData on  AttCHECKINOUT.UserID = EmployeesData.UserIDInAttFile
                                    left join [Machines] on AttCHECKINOUT.[sn]= [Machines].[sn]
                                    where  CHECKTIME between '" & DateFrom & "' and '" & DateTo & "'   order by CHECKTIME,TransID "
        Sql.SqlTrueTimeRunQuery(SQLString2)
        GridControl2.DataSource = Sql.SQLDS.Tables(0)
        GridView2.FocusedRowHandle = focusedRow
    End Sub



    Private Sub GridView2_CustomDrawCell(ByVal sender As Object, ByVal e As RowCellCustomDrawEventArgs) Handles GridView2.CustomDrawCell

        Dim ImageIN As Image = My.Resources.User_Blue_icon
        Dim ImageOut As Image = My.Resources.User_Red_icon
        Dim ImageIN2 As Image = My.Resources.User_Green_icon
        Dim ImageOut2 As Image = My.Resources.User_Orange_icon
        Dim View As GridView = CType(sender, GridView)


        If e.Column.FieldName = "CHECKTYPE" Then
            Dim category As String = View.GetRowCellDisplayText(e.RowHandle, View.Columns("CHECKTYPE"))
            If category = "دخول" Then
                e.Graphics.DrawImage(ImageIN, e.Bounds.Location)
                e.DisplayText = "دخول"
                e.Appearance.Options.CancelUpdate()
            End If
            If category = "خروج" Then
                e.Graphics.DrawImage(ImageOut, e.Bounds.Location)
                e.DisplayText = "خروج"
            End If
            If category = "دخول مغادرة" Then
                e.Graphics.DrawImage(ImageIN2, e.Bounds.Location)
                e.DisplayText = "دخول مغادرة"
            End If
            If category = "خروج مغادرة" Then
                e.Graphics.DrawImage(ImageOut2, e.Bounds.Location)
                e.DisplayText = "خروج مغادرة"
            End If
            If category = String.Empty Then
            End If
        End If




    End Sub



    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs) Handles BtnAddAttTrans.Click
        Try
            Dim EmpNmaeValu As String = LookUpEdit1.EditValue
            Dim EmpNmae As String = LookUpEdit1.Text
            Dim AttDateTime As String = Format(DateEdit3.DateTime, "yyyy-MM-dd HH:mm")
            Dim AttType As String = LookUpEdit2.Text
            Dim AttTypeValue As String = LookUpEdit2.EditValue
            Dim MsgString As String = EmpNmae & " : " & AttDateTime & " : " & AttType

            If EmpNmaeValu = String.Empty Then XtraMessageBox.Show("الموظف فارغ", "خطأ", MessageBoxButtons.OK, MessageBoxIcon.Error) : Exit Sub
            If AttDateTime = String.Empty Then XtraMessageBox.Show(" وقت الحركة فارغ", "خطأ", MessageBoxButtons.OK, MessageBoxIcon.Error) : Exit Sub
            If AttTypeValue = String.Empty Then XtraMessageBox.Show(" نوع الحركة فارغ", "خطأ", MessageBoxButtons.OK, MessageBoxIcon.Error) : Exit Sub


            Dim Msg As DialogResult = XtraMessageBox.Show("  هل تريد ادخال الحركة   " & MsgString, "تأكيد", MessageBoxButtons.YesNo)
            If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub


            Dim InsertAttString As String = "Insert Into AttCHECKINOUT (USERID,CHECKTIME,CHECKTYPE,EditedDate,EditedType,Edited) Values
                                            (" & EmpNmaeValu & " , '" & AttDateTime & "' , '" & AttTypeValue & "' , GETDATE() , 'Insert',1)"

            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(InsertAttString)

            '   GetUsersTable()

            LoadAttData()


        Catch ex As Exception
            MsgBox(ex.ToString)
            MsgBox("خطا : لم يتم ادخال الحركة")
        End Try

    End Sub



    Private Sub RepositoryItemButonDelet_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryItemButtonDelet.ButtonClick

        Try
            '  MsgBox(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTIME"))
            Dim CHECKTYPE As String = CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTYPE"), String)
            Dim CHECKTime As String = Format(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTIME"), "yyyy-MM-dd HH:mm")
            '   MsgBox(CHECKTime)
            Dim Msg As DialogResult = XtraMessageBox.Show("هل تريد حذف الحركة", "تأكيد", MessageBoxButtons.YesNo)
            If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub
            Dim USERID As String = CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "USERID"), String)
            ArchiveTrans(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "TransID"), CHECKTime, CHECKTYPE, "Delete", USERID)
            Dim DeleteString As String = " Delete from  [AttCHECKINOUT]  where [ID]=" & CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "TransID"), String)

            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(DeleteString)
            LoadAttData()
        Catch ex As Exception
            MsgBox(ex.ToString)
            MsgBox("لم يتم حذف الحركة")
        End Try


    End Sub

    Private Sub RepositoryItemButtonEdit_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles RepositoryItemButtonEdit.ButtonClick

        If GlobalVariables._AttAllowEditAttTrans = False Then
            XtraMessageBox.Show("لا يوجد صلاحية لتعديل الحركة")
            Exit Sub
        End If


        Try
            Dim Msg As DialogResult = XtraMessageBox.Show("هل تريد تعديل الحركة", "تأكيد", MessageBoxButtons.YesNo)
            If Msg = System.Windows.Forms.DialogResult.No Then Exit Sub
            Dim CHECKTYPE As String = CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTYPE"), String)
            '  Dim CHECKTime As DateTime = CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTIME"), DateTime)
            Dim CHECKTime As String = Format(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTIME"), "yyyy-MM-dd HH:mm")
            Dim CurrDateTime As String = Format(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "CHECKTIME"), "yyyy-MM-dd HH:mm")
            Dim USERID As String = CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "USERID"), String)
            ArchiveTrans(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "TransID"), CHECKTime, CHECKTYPE, "Update", USERID)

            Dim UpdateString As String = " Update [AttCHECKINOUT] set EditedType = 'Update', CHECKTIME ='" & CurrDateTime & "' ,CHECKTYPE= '" & CHECKTYPE & "' , [EditedDate]=GETDATE() where [ID]=" & CType(GridView2.GetRowCellValue(GridView2.FocusedRowHandle, "TransID"), String)
            Dim sql As New SQLControl
            sql.SqlTrueTimeRunQuery(UpdateString)
            LoadAttData()
        Catch ex As Exception
            MsgBox(ex.ToString)
            MsgBox("خطا : لم يتم تعديل الحركة")
        End Try
    End Sub





    Private Sub SimpleButton2_Click_1(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        GetTransToGrid()
    End Sub

    Public Sub GetTransToGrid()

        Try

            SplashScreenManager1.ShowWaitForm()
            SplashScreenManager1.SetWaitFormCaption("جاري قراءة ملف بيانات الساعة")
            Threading.Thread.Sleep(25)

            Dim FromDate As String = Format(DateEdit1.DateTime, "yyyy-MM-dd") & " 00:00:00"
            Dim ToooDate As String = Format(DateEdit2.DateTime, "yyyy-MM-dd") & " 23:59:59"
            Dim sql As New SQLControl



            SplashScreenManager1.SetWaitFormDescription("تم قراءة " & " " & MyGlobalString & " " & "حركة جديدة")
            SplashScreenManager1.SetWaitFormCaption("جاري معالجة البيانات")

            '  ProcessTrans(Me.DateEdit1, Me.DateEdit2)

            '    LoadInOutTable()             ' تحميل بيانات جدول الدخول والخروج

            LoadAttData()             ' بيانات الدخول والخروج من جدول attendent

            '      InsertingNewWmployees()        ' تعريف الموظفين الجدد الذين لهم حركات

            SplashScreenManager1.CloseWaitForm()

        Catch ex As Exception
            MsgBox(ex.ToString)
            WaitForm11.Hide()
            Exit Sub
        End Try

        GridView2.BestFitColumns()
    End Sub
    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs)
        'Dim answer = MsgBox("هل تريد الغاء معالجة البيانات", vbYesNo)
        'If answer = vbYes Then
        '    Dim SQLString As String = "  Delete FROM [CheckInOut]"
        '    Dim SQLUpdate As String = "  Delete FROM  [AttCHECKINOUT]  "
        '    Dim sql As New SQLControl
        '    sql.SqlTrueTimeRunQuery(SQLString)
        '    sql.SqlTrueTimeRunQuery(SQLUpdate)



        '    Dim con = New System.Data.OleDb.OleDbConnection()
        '    con.ConnectionString = AttConectionString()
        '    con.Open()
        '    Dim SQLString2 As String = " Update CHECKINOUT set AttProcess = Null   "
        '    Dim cmd As OleDbCommand = New OleDbCommand(SQLString2, con)
        '    cmd.ExecuteNonQuery()
        '    cmd.Dispose()
        '    con.Close()


        '    MsgBox("تم الغاء معالجة البيانات")
        'End If
    End Sub



    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        ReadClock.Show()
    End Sub




    Private Sub GridView2_CustomDrawRowIndicator(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs) Handles GridView2.CustomDrawRowIndicator
        Dim gw As GridView = TryCast(sender, GridView)
        If e.RowHandle >= 0 Then
            e.Info.DisplayText = (e.RowHandle + 1).ToString
        End If
    End Sub

    Private Sub GridControl2_Click(sender As Object, e As EventArgs) Handles GridControl2.Click

    End Sub

    Private Sub TextEdit2_EditValueChanged(sender As Object, e As EventArgs) Handles TextEdit2.EditValueChanged

    End Sub

    Private Sub NavigationPane1_Click(sender As Object, e As EventArgs) Handles NavigationPane1.Click

    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        GridControl2.ShowPrintPreview()
    End Sub
    Private Sub GetAccess_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        If CheckIfFormExist(Me.Name) = False Or HasAccessOnForm(Me.Name, "QueryAccess") = False Then
            Me.Close()
            MsgBox("لا يوجد صلاحية")
        End If
    End Sub
End Class